// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ChecklistTemplateEPPRepository is an autogenerated mock type for the ChecklistTemplateEPPRepository type
type ChecklistTemplateEPPRepository struct {
	mock.Mock
}

type ChecklistTemplateEPPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChecklistTemplateEPPRepository) EXPECT() *ChecklistTemplateEPPRepository_Expecter {
	return &ChecklistTemplateEPPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *ChecklistTemplateEPPRepository) Create(ctx context.Context, item *operations.ChecklistTemplateEPP) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.ChecklistTemplateEPP) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateEPPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChecklistTemplateEPPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.ChecklistTemplateEPP
func (_e *ChecklistTemplateEPPRepository_Expecter) Create(ctx interface{}, item interface{}) *ChecklistTemplateEPPRepository_Create_Call {
	return &ChecklistTemplateEPPRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *ChecklistTemplateEPPRepository_Create_Call) Run(run func(ctx context.Context, item *operations.ChecklistTemplateEPP)) *ChecklistTemplateEPPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.ChecklistTemplateEPP))
	})
	return _c
}

func (_c *ChecklistTemplateEPPRepository_Create_Call) Return(_a0 error) *ChecklistTemplateEPPRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateEPPRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.ChecklistTemplateEPP) error) *ChecklistTemplateEPPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateEPPRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateEPPRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ChecklistTemplateEPPRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateEPPRepository_Expecter) Delete(ctx interface{}, id interface{}) *ChecklistTemplateEPPRepository_Delete_Call {
	return &ChecklistTemplateEPPRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ChecklistTemplateEPPRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateEPPRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateEPPRepository_Delete_Call) Return(_a0 error) *ChecklistTemplateEPPRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateEPPRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ChecklistTemplateEPPRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateEPPRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.ChecklistTemplateEPP, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.ChecklistTemplateEPP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.ChecklistTemplateEPP, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.ChecklistTemplateEPP); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ChecklistTemplateEPP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateEPPRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ChecklistTemplateEPPRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateEPPRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ChecklistTemplateEPPRepository_GetByID_Call {
	return &ChecklistTemplateEPPRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ChecklistTemplateEPPRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateEPPRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateEPPRepository_GetByID_Call) Return(_a0 *operations.ChecklistTemplateEPP, _a1 error) *ChecklistTemplateEPPRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateEPPRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.ChecklistTemplateEPP, error)) *ChecklistTemplateEPPRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTemplate provides a mock function with given fields: ctx, templateID
func (_m *ChecklistTemplateEPPRepository) ListByTemplate(ctx context.Context, templateID uuid.UUID) ([]operations.ChecklistTemplateEPP, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTemplate")
	}

	var r0 []operations.ChecklistTemplateEPP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateEPP, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.ChecklistTemplateEPP); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.ChecklistTemplateEPP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateEPPRepository_ListByTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTemplate'
type ChecklistTemplateEPPRepository_ListByTemplate_Call struct {
	*mock.Call
}

// ListByTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID uuid.UUID
func (_e *ChecklistTemplateEPPRepository_Expecter) ListByTemplate(ctx interface{}, templateID interface{}) *ChecklistTemplateEPPRepository_ListByTemplate_Call {
	return &ChecklistTemplateEPPRepository_ListByTemplate_Call{Call: _e.mock.On("ListByTemplate", ctx, templateID)}
}

func (_c *ChecklistTemplateEPPRepository_ListByTemplate_Call) Run(run func(ctx context.Context, templateID uuid.UUID)) *ChecklistTemplateEPPRepository_ListByTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateEPPRepository_ListByTemplate_Call) Return(_a0 []operations.ChecklistTemplateEPP, _a1 error) *ChecklistTemplateEPPRepository_ListByTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateEPPRepository_ListByTemplate_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateEPP, error)) *ChecklistTemplateEPPRepository_ListByTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecklistTemplateEPPRepository creates a new instance of ChecklistTemplateEPPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecklistTemplateEPPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChecklistTemplateEPPRepository {
	mock := &ChecklistTemplateEPPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
