// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ChecklistTemplateToolRepository is an autogenerated mock type for the ChecklistTemplateToolRepository type
type ChecklistTemplateToolRepository struct {
	mock.Mock
}

type ChecklistTemplateToolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChecklistTemplateToolRepository) EXPECT() *ChecklistTemplateToolRepository_Expecter {
	return &ChecklistTemplateToolRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *ChecklistTemplateToolRepository) Create(ctx context.Context, item *operations.ChecklistTemplateTool) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.ChecklistTemplateTool) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateToolRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChecklistTemplateToolRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.ChecklistTemplateTool
func (_e *ChecklistTemplateToolRepository_Expecter) Create(ctx interface{}, item interface{}) *ChecklistTemplateToolRepository_Create_Call {
	return &ChecklistTemplateToolRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *ChecklistTemplateToolRepository_Create_Call) Run(run func(ctx context.Context, item *operations.ChecklistTemplateTool)) *ChecklistTemplateToolRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.ChecklistTemplateTool))
	})
	return _c
}

func (_c *ChecklistTemplateToolRepository_Create_Call) Return(_a0 error) *ChecklistTemplateToolRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateToolRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.ChecklistTemplateTool) error) *ChecklistTemplateToolRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateToolRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateToolRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ChecklistTemplateToolRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateToolRepository_Expecter) Delete(ctx interface{}, id interface{}) *ChecklistTemplateToolRepository_Delete_Call {
	return &ChecklistTemplateToolRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ChecklistTemplateToolRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateToolRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateToolRepository_Delete_Call) Return(_a0 error) *ChecklistTemplateToolRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateToolRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ChecklistTemplateToolRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateToolRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.ChecklistTemplateTool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.ChecklistTemplateTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.ChecklistTemplateTool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.ChecklistTemplateTool); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ChecklistTemplateTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateToolRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ChecklistTemplateToolRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateToolRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ChecklistTemplateToolRepository_GetByID_Call {
	return &ChecklistTemplateToolRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ChecklistTemplateToolRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateToolRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateToolRepository_GetByID_Call) Return(_a0 *operations.ChecklistTemplateTool, _a1 error) *ChecklistTemplateToolRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateToolRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.ChecklistTemplateTool, error)) *ChecklistTemplateToolRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTemplate provides a mock function with given fields: ctx, templateID
func (_m *ChecklistTemplateToolRepository) ListByTemplate(ctx context.Context, templateID uuid.UUID) ([]operations.ChecklistTemplateTool, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTemplate")
	}

	var r0 []operations.ChecklistTemplateTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateTool, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.ChecklistTemplateTool); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.ChecklistTemplateTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateToolRepository_ListByTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTemplate'
type ChecklistTemplateToolRepository_ListByTemplate_Call struct {
	*mock.Call
}

// ListByTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID uuid.UUID
func (_e *ChecklistTemplateToolRepository_Expecter) ListByTemplate(ctx interface{}, templateID interface{}) *ChecklistTemplateToolRepository_ListByTemplate_Call {
	return &ChecklistTemplateToolRepository_ListByTemplate_Call{Call: _e.mock.On("ListByTemplate", ctx, templateID)}
}

func (_c *ChecklistTemplateToolRepository_ListByTemplate_Call) Run(run func(ctx context.Context, templateID uuid.UUID)) *ChecklistTemplateToolRepository_ListByTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateToolRepository_ListByTemplate_Call) Return(_a0 []operations.ChecklistTemplateTool, _a1 error) *ChecklistTemplateToolRepository_ListByTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateToolRepository_ListByTemplate_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateTool, error)) *ChecklistTemplateToolRepository_ListByTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecklistTemplateToolRepository creates a new instance of ChecklistTemplateToolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecklistTemplateToolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChecklistTemplateToolRepository {
	mock := &ChecklistTemplateToolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
