// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ChecklistTemplateMaterialRepository is an autogenerated mock type for the ChecklistTemplateMaterialRepository type
type ChecklistTemplateMaterialRepository struct {
	mock.Mock
}

type ChecklistTemplateMaterialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChecklistTemplateMaterialRepository) EXPECT() *ChecklistTemplateMaterialRepository_Expecter {
	return &ChecklistTemplateMaterialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *ChecklistTemplateMaterialRepository) Create(ctx context.Context, item *operations.ChecklistTemplateMaterial) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.ChecklistTemplateMaterial) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateMaterialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChecklistTemplateMaterialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.ChecklistTemplateMaterial
func (_e *ChecklistTemplateMaterialRepository_Expecter) Create(ctx interface{}, item interface{}) *ChecklistTemplateMaterialRepository_Create_Call {
	return &ChecklistTemplateMaterialRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *ChecklistTemplateMaterialRepository_Create_Call) Run(run func(ctx context.Context, item *operations.ChecklistTemplateMaterial)) *ChecklistTemplateMaterialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.ChecklistTemplateMaterial))
	})
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_Create_Call) Return(_a0 error) *ChecklistTemplateMaterialRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.ChecklistTemplateMaterial) error) *ChecklistTemplateMaterialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateMaterialRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateMaterialRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ChecklistTemplateMaterialRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateMaterialRepository_Expecter) Delete(ctx interface{}, id interface{}) *ChecklistTemplateMaterialRepository_Delete_Call {
	return &ChecklistTemplateMaterialRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ChecklistTemplateMaterialRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateMaterialRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_Delete_Call) Return(_a0 error) *ChecklistTemplateMaterialRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ChecklistTemplateMaterialRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateMaterialRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.ChecklistTemplateMaterial, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.ChecklistTemplateMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.ChecklistTemplateMaterial, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.ChecklistTemplateMaterial); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ChecklistTemplateMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateMaterialRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ChecklistTemplateMaterialRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateMaterialRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ChecklistTemplateMaterialRepository_GetByID_Call {
	return &ChecklistTemplateMaterialRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ChecklistTemplateMaterialRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateMaterialRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_GetByID_Call) Return(_a0 *operations.ChecklistTemplateMaterial, _a1 error) *ChecklistTemplateMaterialRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.ChecklistTemplateMaterial, error)) *ChecklistTemplateMaterialRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTemplate provides a mock function with given fields: ctx, templateID
func (_m *ChecklistTemplateMaterialRepository) ListByTemplate(ctx context.Context, templateID uuid.UUID) ([]operations.ChecklistTemplateMaterial, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTemplate")
	}

	var r0 []operations.ChecklistTemplateMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateMaterial, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.ChecklistTemplateMaterial); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.ChecklistTemplateMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateMaterialRepository_ListByTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTemplate'
type ChecklistTemplateMaterialRepository_ListByTemplate_Call struct {
	*mock.Call
}

// ListByTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID uuid.UUID
func (_e *ChecklistTemplateMaterialRepository_Expecter) ListByTemplate(ctx interface{}, templateID interface{}) *ChecklistTemplateMaterialRepository_ListByTemplate_Call {
	return &ChecklistTemplateMaterialRepository_ListByTemplate_Call{Call: _e.mock.On("ListByTemplate", ctx, templateID)}
}

func (_c *ChecklistTemplateMaterialRepository_ListByTemplate_Call) Run(run func(ctx context.Context, templateID uuid.UUID)) *ChecklistTemplateMaterialRepository_ListByTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_ListByTemplate_Call) Return(_a0 []operations.ChecklistTemplateMaterial, _a1 error) *ChecklistTemplateMaterialRepository_ListByTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateMaterialRepository_ListByTemplate_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.ChecklistTemplateMaterial, error)) *ChecklistTemplateMaterialRepository_ListByTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecklistTemplateMaterialRepository creates a new instance of ChecklistTemplateMaterialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecklistTemplateMaterialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChecklistTemplateMaterialRepository {
	mock := &ChecklistTemplateMaterialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
