// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// ChecklistTemplateRepository is an autogenerated mock type for the ChecklistTemplateRepository type
type ChecklistTemplateRepository struct {
	mock.Mock
}

type ChecklistTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChecklistTemplateRepository) EXPECT() *ChecklistTemplateRepository_Expecter {
	return &ChecklistTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tmpl
func (_m *ChecklistTemplateRepository) Create(ctx context.Context, tmpl *inventory.ChecklistTemplate) error {
	ret := _m.Called(ctx, tmpl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.ChecklistTemplate) error); ok {
		r0 = rf(ctx, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChecklistTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tmpl *inventory.ChecklistTemplate
func (_e *ChecklistTemplateRepository_Expecter) Create(ctx interface{}, tmpl interface{}) *ChecklistTemplateRepository_Create_Call {
	return &ChecklistTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, tmpl)}
}

func (_c *ChecklistTemplateRepository_Create_Call) Run(run func(ctx context.Context, tmpl *inventory.ChecklistTemplate)) *ChecklistTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.ChecklistTemplate))
	})
	return _c
}

func (_c *ChecklistTemplateRepository_Create_Call) Return(_a0 error) *ChecklistTemplateRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.ChecklistTemplate) error) *ChecklistTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ChecklistTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateRepository_Expecter) Delete(ctx interface{}, id interface{}) *ChecklistTemplateRepository_Delete_Call {
	return &ChecklistTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ChecklistTemplateRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateRepository_Delete_Call) Return(_a0 error) *ChecklistTemplateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ChecklistTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ChecklistTemplateRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.ChecklistTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.ChecklistTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.ChecklistTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.ChecklistTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.ChecklistTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ChecklistTemplateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChecklistTemplateRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ChecklistTemplateRepository_GetByID_Call {
	return &ChecklistTemplateRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ChecklistTemplateRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChecklistTemplateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChecklistTemplateRepository_GetByID_Call) Return(_a0 *inventory.ChecklistTemplate, _a1 error) *ChecklistTemplateRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.ChecklistTemplate, error)) *ChecklistTemplateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *ChecklistTemplateRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.ChecklistTemplate], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.ChecklistTemplate]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.ChecklistTemplate], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.ChecklistTemplate]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.ChecklistTemplate])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChecklistTemplateRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ChecklistTemplateRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *ChecklistTemplateRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *ChecklistTemplateRepository_List_Call {
	return &ChecklistTemplateRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *ChecklistTemplateRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *ChecklistTemplateRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ChecklistTemplateRepository_List_Call) Return(_a0 *repository.ListResult[inventory.ChecklistTemplate], _a1 error) *ChecklistTemplateRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChecklistTemplateRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.ChecklistTemplate], error)) *ChecklistTemplateRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, tmpl
func (_m *ChecklistTemplateRepository) Update(ctx context.Context, id uuid.UUID, tmpl *inventory.ChecklistTemplate) error {
	ret := _m.Called(ctx, id, tmpl)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.ChecklistTemplate) error); ok {
		r0 = rf(ctx, id, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChecklistTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ChecklistTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tmpl *inventory.ChecklistTemplate
func (_e *ChecklistTemplateRepository_Expecter) Update(ctx interface{}, id interface{}, tmpl interface{}) *ChecklistTemplateRepository_Update_Call {
	return &ChecklistTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, tmpl)}
}

func (_c *ChecklistTemplateRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, tmpl *inventory.ChecklistTemplate)) *ChecklistTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.ChecklistTemplate))
	})
	return _c
}

func (_c *ChecklistTemplateRepository_Update_Call) Return(_a0 error) *ChecklistTemplateRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChecklistTemplateRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.ChecklistTemplate) error) *ChecklistTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecklistTemplateRepository creates a new instance of ChecklistTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecklistTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChecklistTemplateRepository {
	mock := &ChecklistTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
