// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	core "localis-backend/internal/model/core"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	shared "localis-backend/internal/model/shared"

	uuid "github.com/google/uuid"
)

// CorePlanAuditLogRepository is an autogenerated mock type for the CorePlanAuditLogRepository type
type CorePlanAuditLogRepository struct {
	mock.Mock
}

type CorePlanAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CorePlanAuditLogRepository) EXPECT() *CorePlanAuditLogRepository_Expecter {
	return &CorePlanAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entry
func (_m *CorePlanAuditLogRepository) Create(ctx context.Context, entry *core.PlanAuditLog) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.PlanAuditLog) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CorePlanAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CorePlanAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *core.PlanAuditLog
func (_e *CorePlanAuditLogRepository_Expecter) Create(ctx interface{}, entry interface{}) *CorePlanAuditLogRepository_Create_Call {
	return &CorePlanAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *CorePlanAuditLogRepository_Create_Call) Run(run func(ctx context.Context, entry *core.PlanAuditLog)) *CorePlanAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.PlanAuditLog))
	})
	return _c
}

func (_c *CorePlanAuditLogRepository_Create_Call) Return(_a0 error) *CorePlanAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CorePlanAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *core.PlanAuditLog) error) *CorePlanAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CorePlanAuditLogRepository) GetByID(ctx context.Context, id uuid.UUID) (*core.PlanAuditLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *core.PlanAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*core.PlanAuditLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *core.PlanAuditLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.PlanAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorePlanAuditLogRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CorePlanAuditLogRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CorePlanAuditLogRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CorePlanAuditLogRepository_GetByID_Call {
	return &CorePlanAuditLogRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CorePlanAuditLogRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CorePlanAuditLogRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CorePlanAuditLogRepository_GetByID_Call) Return(_a0 *core.PlanAuditLog, _a1 error) *CorePlanAuditLogRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorePlanAuditLogRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*core.PlanAuditLog, error)) *CorePlanAuditLogRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *CorePlanAuditLogRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[core.PlanAuditLog], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[core.PlanAuditLog]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[core.PlanAuditLog], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[core.PlanAuditLog]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[core.PlanAuditLog])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorePlanAuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CorePlanAuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *CorePlanAuditLogRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *CorePlanAuditLogRepository_List_Call {
	return &CorePlanAuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *CorePlanAuditLogRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *CorePlanAuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *CorePlanAuditLogRepository_List_Call) Return(_a0 *repository.ListResult[core.PlanAuditLog], _a1 error) *CorePlanAuditLogRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorePlanAuditLogRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[core.PlanAuditLog], error)) *CorePlanAuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *CorePlanAuditLogRepository) ListByEntity(ctx context.Context, entityType shared.AuditEntityType, entityID uuid.UUID) ([]core.PlanAuditLog, error) {
	ret := _m.Called(ctx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for ListByEntity")
	}

	var r0 []core.PlanAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.AuditEntityType, uuid.UUID) ([]core.PlanAuditLog, error)); ok {
		return rf(ctx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.AuditEntityType, uuid.UUID) []core.PlanAuditLog); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PlanAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.AuditEntityType, uuid.UUID) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorePlanAuditLogRepository_ListByEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEntity'
type CorePlanAuditLogRepository_ListByEntity_Call struct {
	*mock.Call
}

// ListByEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entityType shared.AuditEntityType
//   - entityID uuid.UUID
func (_e *CorePlanAuditLogRepository_Expecter) ListByEntity(ctx interface{}, entityType interface{}, entityID interface{}) *CorePlanAuditLogRepository_ListByEntity_Call {
	return &CorePlanAuditLogRepository_ListByEntity_Call{Call: _e.mock.On("ListByEntity", ctx, entityType, entityID)}
}

func (_c *CorePlanAuditLogRepository_ListByEntity_Call) Run(run func(ctx context.Context, entityType shared.AuditEntityType, entityID uuid.UUID)) *CorePlanAuditLogRepository_ListByEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.AuditEntityType), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CorePlanAuditLogRepository_ListByEntity_Call) Return(_a0 []core.PlanAuditLog, _a1 error) *CorePlanAuditLogRepository_ListByEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorePlanAuditLogRepository_ListByEntity_Call) RunAndReturn(run func(context.Context, shared.AuditEntityType, uuid.UUID) ([]core.PlanAuditLog, error)) *CorePlanAuditLogRepository_ListByEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewCorePlanAuditLogRepository creates a new instance of CorePlanAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCorePlanAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CorePlanAuditLogRepository {
	mock := &CorePlanAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
