// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	core "localis-backend/internal/model/core"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// CoreTechRoleRepository is an autogenerated mock type for the CoreTechRoleRepository type
type CoreTechRoleRepository struct {
	mock.Mock
}

type CoreTechRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreTechRoleRepository) EXPECT() *CoreTechRoleRepository_Expecter {
	return &CoreTechRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role
func (_m *CoreTechRoleRepository) Create(ctx context.Context, role *core.TechRole) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.TechRole) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreTechRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CoreTechRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *core.TechRole
func (_e *CoreTechRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *CoreTechRoleRepository_Create_Call {
	return &CoreTechRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *CoreTechRoleRepository_Create_Call) Run(run func(ctx context.Context, role *core.TechRole)) *CoreTechRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.TechRole))
	})
	return _c
}

func (_c *CoreTechRoleRepository_Create_Call) Return(_a0 error) *CoreTechRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreTechRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *core.TechRole) error) *CoreTechRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CoreTechRoleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreTechRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CoreTechRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CoreTechRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *CoreTechRoleRepository_Delete_Call {
	return &CoreTechRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CoreTechRoleRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CoreTechRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CoreTechRoleRepository_Delete_Call) Return(_a0 error) *CoreTechRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreTechRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *CoreTechRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CoreTechRoleRepository) GetByID(ctx context.Context, id uuid.UUID) (*core.TechRole, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *core.TechRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*core.TechRole, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *core.TechRole); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.TechRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreTechRoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CoreTechRoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CoreTechRoleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CoreTechRoleRepository_GetByID_Call {
	return &CoreTechRoleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CoreTechRoleRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CoreTechRoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CoreTechRoleRepository_GetByID_Call) Return(_a0 *core.TechRole, _a1 error) *CoreTechRoleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreTechRoleRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*core.TechRole, error)) *CoreTechRoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *CoreTechRoleRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[core.TechRole], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[core.TechRole]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[core.TechRole], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[core.TechRole]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[core.TechRole])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreTechRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CoreTechRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *CoreTechRoleRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *CoreTechRoleRepository_List_Call {
	return &CoreTechRoleRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *CoreTechRoleRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *CoreTechRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *CoreTechRoleRepository_List_Call) Return(_a0 *repository.ListResult[core.TechRole], _a1 error) *CoreTechRoleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreTechRoleRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[core.TechRole], error)) *CoreTechRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, role
func (_m *CoreTechRoleRepository) Update(ctx context.Context, id uuid.UUID, role *core.TechRole) error {
	ret := _m.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *core.TechRole) error); ok {
		r0 = rf(ctx, id, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreTechRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CoreTechRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - role *core.TechRole
func (_e *CoreTechRoleRepository_Expecter) Update(ctx interface{}, id interface{}, role interface{}) *CoreTechRoleRepository_Update_Call {
	return &CoreTechRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, role)}
}

func (_c *CoreTechRoleRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, role *core.TechRole)) *CoreTechRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*core.TechRole))
	})
	return _c
}

func (_c *CoreTechRoleRepository_Update_Call) Return(_a0 error) *CoreTechRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreTechRoleRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *core.TechRole) error) *CoreTechRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreTechRoleRepository creates a new instance of CoreTechRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreTechRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreTechRoleRepository {
	mock := &CoreTechRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
