// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	core "localis-backend/internal/model/core"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"
)

// CoreUserRepository is an autogenerated mock type for the CoreUserRepository type
type CoreUserRepository struct {
	mock.Mock
}

type CoreUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreUserRepository) EXPECT() *CoreUserRepository_Expecter {
	return &CoreUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *CoreUserRepository) Create(ctx context.Context, user *core.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CoreUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *core.User
func (_e *CoreUserRepository_Expecter) Create(ctx interface{}, user interface{}) *CoreUserRepository_Create_Call {
	return &CoreUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *CoreUserRepository_Create_Call) Run(run func(ctx context.Context, user *core.User)) *CoreUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.User))
	})
	return _c
}

func (_c *CoreUserRepository_Create_Call) Return(_a0 error) *CoreUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreUserRepository_Create_Call) RunAndReturn(run func(context.Context, *core.User) error) *CoreUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CoreUserRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CoreUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CoreUserRepository_Expecter) Delete(ctx interface{}, id interface{}) *CoreUserRepository_Delete_Call {
	return &CoreUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CoreUserRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CoreUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoreUserRepository_Delete_Call) Return(_a0 error) *CoreUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreUserRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CoreUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CoreUserRepository) GetByID(ctx context.Context, id string) (*core.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *core.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CoreUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CoreUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CoreUserRepository_GetByID_Call {
	return &CoreUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CoreUserRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CoreUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoreUserRepository_GetByID_Call) Return(_a0 *core.User, _a1 error) *CoreUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*core.User, error)) *CoreUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *CoreUserRepository) GetByEmail(ctx context.Context, email string) (*core.UserWithPassword, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *core.UserWithPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.UserWithPassword, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.UserWithPassword); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.UserWithPassword)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type CoreUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *CoreUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *CoreUserRepository_GetByEmail_Call {
	return &CoreUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *CoreUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *CoreUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoreUserRepository_GetByEmail_Call) Return(_a0 *core.UserWithPassword, _a1 error) *CoreUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*core.UserWithPassword, error)) *CoreUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *CoreUserRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[core.User], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[core.User]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[core.User], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[core.User]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[core.User])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreUserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CoreUserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *CoreUserRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *CoreUserRepository_List_Call {
	return &CoreUserRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *CoreUserRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *CoreUserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *CoreUserRepository_List_Call) Return(_a0 *repository.ListResult[core.User], _a1 error) *CoreUserRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreUserRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[core.User], error)) *CoreUserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, user
func (_m *CoreUserRepository) Update(ctx context.Context, id string, user *core.User) error {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *core.User) error); ok {
		r0 = rf(ctx, id, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CoreUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user *core.User
func (_e *CoreUserRepository_Expecter) Update(ctx interface{}, id interface{}, user interface{}) *CoreUserRepository_Update_Call {
	return &CoreUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, user)}
}

func (_c *CoreUserRepository_Update_Call) Run(run func(ctx context.Context, id string, user *core.User)) *CoreUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*core.User))
	})
	return _c
}

func (_c *CoreUserRepository_Update_Call) Return(_a0 error) *CoreUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreUserRepository_Update_Call) RunAndReturn(run func(context.Context, string, *core.User) error) *CoreUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreUserRepository creates a new instance of CoreUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreUserRepository {
	mock := &CoreUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
