// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	customers "localis-backend/internal/model/customers"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CustomerAddressPartnerRepository is an autogenerated mock type for the CustomerAddressPartnerRepository type
type CustomerAddressPartnerRepository struct {
	mock.Mock
}

type CustomerAddressPartnerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerAddressPartnerRepository) EXPECT() *CustomerAddressPartnerRepository_Expecter {
	return &CustomerAddressPartnerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cap
func (_m *CustomerAddressPartnerRepository) Create(ctx context.Context, cap *customers.CustomerAddressPartner) error {
	ret := _m.Called(ctx, cap)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customers.CustomerAddressPartner) error); ok {
		r0 = rf(ctx, cap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerAddressPartnerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomerAddressPartnerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cap *customers.CustomerAddressPartner
func (_e *CustomerAddressPartnerRepository_Expecter) Create(ctx interface{}, cap interface{}) *CustomerAddressPartnerRepository_Create_Call {
	return &CustomerAddressPartnerRepository_Create_Call{Call: _e.mock.On("Create", ctx, cap)}
}

func (_c *CustomerAddressPartnerRepository_Create_Call) Run(run func(ctx context.Context, cap *customers.CustomerAddressPartner)) *CustomerAddressPartnerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customers.CustomerAddressPartner))
	})
	return _c
}

func (_c *CustomerAddressPartnerRepository_Create_Call) Return(_a0 error) *CustomerAddressPartnerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerAddressPartnerRepository_Create_Call) RunAndReturn(run func(context.Context, *customers.CustomerAddressPartner) error) *CustomerAddressPartnerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CustomerAddressPartnerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerAddressPartnerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CustomerAddressPartnerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CustomerAddressPartnerRepository_Expecter) Delete(ctx interface{}, id interface{}) *CustomerAddressPartnerRepository_Delete_Call {
	return &CustomerAddressPartnerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CustomerAddressPartnerRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CustomerAddressPartnerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressPartnerRepository_Delete_Call) Return(_a0 error) *CustomerAddressPartnerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerAddressPartnerRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *CustomerAddressPartnerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CustomerAddressPartnerRepository) GetByID(ctx context.Context, id uuid.UUID) (*customers.CustomerAddressPartner, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *customers.CustomerAddressPartner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customers.CustomerAddressPartner, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customers.CustomerAddressPartner); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.CustomerAddressPartner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerAddressPartnerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CustomerAddressPartnerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CustomerAddressPartnerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CustomerAddressPartnerRepository_GetByID_Call {
	return &CustomerAddressPartnerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CustomerAddressPartnerRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CustomerAddressPartnerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressPartnerRepository_GetByID_Call) Return(_a0 *customers.CustomerAddressPartner, _a1 error) *CustomerAddressPartnerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerAddressPartnerRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*customers.CustomerAddressPartner, error)) *CustomerAddressPartnerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomerAddress provides a mock function with given fields: ctx, caID
func (_m *CustomerAddressPartnerRepository) ListByCustomerAddress(ctx context.Context, caID uuid.UUID) ([]customers.CustomerAddressPartner, error) {
	ret := _m.Called(ctx, caID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomerAddress")
	}

	var r0 []customers.CustomerAddressPartner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]customers.CustomerAddressPartner, error)); ok {
		return rf(ctx, caID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []customers.CustomerAddressPartner); ok {
		r0 = rf(ctx, caID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customers.CustomerAddressPartner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, caID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerAddressPartnerRepository_ListByCustomerAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomerAddress'
type CustomerAddressPartnerRepository_ListByCustomerAddress_Call struct {
	*mock.Call
}

// ListByCustomerAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - caID uuid.UUID
func (_e *CustomerAddressPartnerRepository_Expecter) ListByCustomerAddress(ctx interface{}, caID interface{}) *CustomerAddressPartnerRepository_ListByCustomerAddress_Call {
	return &CustomerAddressPartnerRepository_ListByCustomerAddress_Call{Call: _e.mock.On("ListByCustomerAddress", ctx, caID)}
}

func (_c *CustomerAddressPartnerRepository_ListByCustomerAddress_Call) Run(run func(ctx context.Context, caID uuid.UUID)) *CustomerAddressPartnerRepository_ListByCustomerAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressPartnerRepository_ListByCustomerAddress_Call) Return(_a0 []customers.CustomerAddressPartner, _a1 error) *CustomerAddressPartnerRepository_ListByCustomerAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerAddressPartnerRepository_ListByCustomerAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]customers.CustomerAddressPartner, error)) *CustomerAddressPartnerRepository_ListByCustomerAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomerAddressPartnerRepository creates a new instance of CustomerAddressPartnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerAddressPartnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerAddressPartnerRepository {
	mock := &CustomerAddressPartnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
