// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	customers "localis-backend/internal/model/customers"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CustomerAddressRepository is an autogenerated mock type for the CustomerAddressRepository type
type CustomerAddressRepository struct {
	mock.Mock
}

type CustomerAddressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerAddressRepository) EXPECT() *CustomerAddressRepository_Expecter {
	return &CustomerAddressRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, addr
func (_m *CustomerAddressRepository) Create(ctx context.Context, addr *customers.CustomerAddress) error {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customers.CustomerAddress) error); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerAddressRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomerAddressRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - addr *customers.CustomerAddress
func (_e *CustomerAddressRepository_Expecter) Create(ctx interface{}, addr interface{}) *CustomerAddressRepository_Create_Call {
	return &CustomerAddressRepository_Create_Call{Call: _e.mock.On("Create", ctx, addr)}
}

func (_c *CustomerAddressRepository_Create_Call) Run(run func(ctx context.Context, addr *customers.CustomerAddress)) *CustomerAddressRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customers.CustomerAddress))
	})
	return _c
}

func (_c *CustomerAddressRepository_Create_Call) Return(_a0 error) *CustomerAddressRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerAddressRepository_Create_Call) RunAndReturn(run func(context.Context, *customers.CustomerAddress) error) *CustomerAddressRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CustomerAddressRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerAddressRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CustomerAddressRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CustomerAddressRepository_Expecter) Delete(ctx interface{}, id interface{}) *CustomerAddressRepository_Delete_Call {
	return &CustomerAddressRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CustomerAddressRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CustomerAddressRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressRepository_Delete_Call) Return(_a0 error) *CustomerAddressRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerAddressRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *CustomerAddressRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CustomerAddressRepository) GetByID(ctx context.Context, id uuid.UUID) (*customers.CustomerAddress, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *customers.CustomerAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customers.CustomerAddress, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customers.CustomerAddress); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.CustomerAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerAddressRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CustomerAddressRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CustomerAddressRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CustomerAddressRepository_GetByID_Call {
	return &CustomerAddressRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CustomerAddressRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CustomerAddressRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressRepository_GetByID_Call) Return(_a0 *customers.CustomerAddress, _a1 error) *CustomerAddressRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerAddressRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*customers.CustomerAddress, error)) *CustomerAddressRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomer provides a mock function with given fields: ctx, customerID
func (_m *CustomerAddressRepository) ListByCustomer(ctx context.Context, customerID uuid.UUID) ([]customers.CustomerAddress, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomer")
	}

	var r0 []customers.CustomerAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]customers.CustomerAddress, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []customers.CustomerAddress); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customers.CustomerAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerAddressRepository_ListByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomer'
type CustomerAddressRepository_ListByCustomer_Call struct {
	*mock.Call
}

// ListByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *CustomerAddressRepository_Expecter) ListByCustomer(ctx interface{}, customerID interface{}) *CustomerAddressRepository_ListByCustomer_Call {
	return &CustomerAddressRepository_ListByCustomer_Call{Call: _e.mock.On("ListByCustomer", ctx, customerID)}
}

func (_c *CustomerAddressRepository_ListByCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *CustomerAddressRepository_ListByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CustomerAddressRepository_ListByCustomer_Call) Return(_a0 []customers.CustomerAddress, _a1 error) *CustomerAddressRepository_ListByCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerAddressRepository_ListByCustomer_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]customers.CustomerAddress, error)) *CustomerAddressRepository_ListByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, addr
func (_m *CustomerAddressRepository) Update(ctx context.Context, id uuid.UUID, addr *customers.CustomerAddress) error {
	ret := _m.Called(ctx, id, addr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *customers.CustomerAddress) error); ok {
		r0 = rf(ctx, id, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerAddressRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CustomerAddressRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - addr *customers.CustomerAddress
func (_e *CustomerAddressRepository_Expecter) Update(ctx interface{}, id interface{}, addr interface{}) *CustomerAddressRepository_Update_Call {
	return &CustomerAddressRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, addr)}
}

func (_c *CustomerAddressRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, addr *customers.CustomerAddress)) *CustomerAddressRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*customers.CustomerAddress))
	})
	return _c
}

func (_c *CustomerAddressRepository_Update_Call) Return(_a0 error) *CustomerAddressRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerAddressRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *customers.CustomerAddress) error) *CustomerAddressRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomerAddressRepository creates a new instance of CustomerAddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerAddressRepository {
	mock := &CustomerAddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
