// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	planning "localis-backend/internal/model/planning"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DailyLoadToolRepository is an autogenerated mock type for the DailyLoadToolRepository type
type DailyLoadToolRepository struct {
	mock.Mock
}

type DailyLoadToolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DailyLoadToolRepository) EXPECT() *DailyLoadToolRepository_Expecter {
	return &DailyLoadToolRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *DailyLoadToolRepository) Create(ctx context.Context, t *planning.DailyLoadTool) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *planning.DailyLoadTool) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadToolRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DailyLoadToolRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *planning.DailyLoadTool
func (_e *DailyLoadToolRepository_Expecter) Create(ctx interface{}, t interface{}) *DailyLoadToolRepository_Create_Call {
	return &DailyLoadToolRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *DailyLoadToolRepository_Create_Call) Run(run func(ctx context.Context, t *planning.DailyLoadTool)) *DailyLoadToolRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*planning.DailyLoadTool))
	})
	return _c
}

func (_c *DailyLoadToolRepository_Create_Call) Return(_a0 error) *DailyLoadToolRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadToolRepository_Create_Call) RunAndReturn(run func(context.Context, *planning.DailyLoadTool) error) *DailyLoadToolRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DailyLoadToolRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadToolRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DailyLoadToolRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DailyLoadToolRepository_Expecter) Delete(ctx interface{}, id interface{}) *DailyLoadToolRepository_Delete_Call {
	return &DailyLoadToolRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *DailyLoadToolRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DailyLoadToolRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadToolRepository_Delete_Call) Return(_a0 error) *DailyLoadToolRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadToolRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *DailyLoadToolRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *DailyLoadToolRepository) GetByID(ctx context.Context, id uuid.UUID) (*planning.DailyLoadTool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *planning.DailyLoadTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*planning.DailyLoadTool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *planning.DailyLoadTool); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*planning.DailyLoadTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DailyLoadToolRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DailyLoadToolRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DailyLoadToolRepository_Expecter) GetByID(ctx interface{}, id interface{}) *DailyLoadToolRepository_GetByID_Call {
	return &DailyLoadToolRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *DailyLoadToolRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DailyLoadToolRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadToolRepository_GetByID_Call) Return(_a0 *planning.DailyLoadTool, _a1 error) *DailyLoadToolRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DailyLoadToolRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*planning.DailyLoadTool, error)) *DailyLoadToolRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPlan provides a mock function with given fields: ctx, planID
func (_m *DailyLoadToolRepository) ListByPlan(ctx context.Context, planID uuid.UUID) ([]planning.DailyLoadTool, error) {
	ret := _m.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for ListByPlan")
	}

	var r0 []planning.DailyLoadTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]planning.DailyLoadTool, error)); ok {
		return rf(ctx, planID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []planning.DailyLoadTool); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]planning.DailyLoadTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DailyLoadToolRepository_ListByPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPlan'
type DailyLoadToolRepository_ListByPlan_Call struct {
	*mock.Call
}

// ListByPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uuid.UUID
func (_e *DailyLoadToolRepository_Expecter) ListByPlan(ctx interface{}, planID interface{}) *DailyLoadToolRepository_ListByPlan_Call {
	return &DailyLoadToolRepository_ListByPlan_Call{Call: _e.mock.On("ListByPlan", ctx, planID)}
}

func (_c *DailyLoadToolRepository_ListByPlan_Call) Run(run func(ctx context.Context, planID uuid.UUID)) *DailyLoadToolRepository_ListByPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadToolRepository_ListByPlan_Call) Return(_a0 []planning.DailyLoadTool, _a1 error) *DailyLoadToolRepository_ListByPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DailyLoadToolRepository_ListByPlan_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]planning.DailyLoadTool, error)) *DailyLoadToolRepository_ListByPlan_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, t
func (_m *DailyLoadToolRepository) Update(ctx context.Context, id uuid.UUID, t *planning.DailyLoadTool) error {
	ret := _m.Called(ctx, id, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *planning.DailyLoadTool) error); ok {
		r0 = rf(ctx, id, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadToolRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DailyLoadToolRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - t *planning.DailyLoadTool
func (_e *DailyLoadToolRepository_Expecter) Update(ctx interface{}, id interface{}, t interface{}) *DailyLoadToolRepository_Update_Call {
	return &DailyLoadToolRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, t)}
}

func (_c *DailyLoadToolRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, t *planning.DailyLoadTool)) *DailyLoadToolRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*planning.DailyLoadTool))
	})
	return _c
}

func (_c *DailyLoadToolRepository_Update_Call) Return(_a0 error) *DailyLoadToolRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadToolRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *planning.DailyLoadTool) error) *DailyLoadToolRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDailyLoadToolRepository creates a new instance of DailyLoadToolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDailyLoadToolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DailyLoadToolRepository {
	mock := &DailyLoadToolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
