// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	planning "localis-backend/internal/model/planning"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DailyLoadMaterialRepository is an autogenerated mock type for the DailyLoadMaterialRepository type
type DailyLoadMaterialRepository struct {
	mock.Mock
}

type DailyLoadMaterialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DailyLoadMaterialRepository) EXPECT() *DailyLoadMaterialRepository_Expecter {
	return &DailyLoadMaterialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *DailyLoadMaterialRepository) Create(ctx context.Context, m *planning.DailyLoadMaterial) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *planning.DailyLoadMaterial) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadMaterialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DailyLoadMaterialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *planning.DailyLoadMaterial
func (_e *DailyLoadMaterialRepository_Expecter) Create(ctx interface{}, m interface{}) *DailyLoadMaterialRepository_Create_Call {
	return &DailyLoadMaterialRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *DailyLoadMaterialRepository_Create_Call) Run(run func(ctx context.Context, m *planning.DailyLoadMaterial)) *DailyLoadMaterialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*planning.DailyLoadMaterial))
	})
	return _c
}

func (_c *DailyLoadMaterialRepository_Create_Call) Return(_a0 error) *DailyLoadMaterialRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadMaterialRepository_Create_Call) RunAndReturn(run func(context.Context, *planning.DailyLoadMaterial) error) *DailyLoadMaterialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DailyLoadMaterialRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadMaterialRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DailyLoadMaterialRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DailyLoadMaterialRepository_Expecter) Delete(ctx interface{}, id interface{}) *DailyLoadMaterialRepository_Delete_Call {
	return &DailyLoadMaterialRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *DailyLoadMaterialRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DailyLoadMaterialRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadMaterialRepository_Delete_Call) Return(_a0 error) *DailyLoadMaterialRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadMaterialRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *DailyLoadMaterialRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *DailyLoadMaterialRepository) GetByID(ctx context.Context, id uuid.UUID) (*planning.DailyLoadMaterial, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *planning.DailyLoadMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*planning.DailyLoadMaterial, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *planning.DailyLoadMaterial); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*planning.DailyLoadMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DailyLoadMaterialRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DailyLoadMaterialRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DailyLoadMaterialRepository_Expecter) GetByID(ctx interface{}, id interface{}) *DailyLoadMaterialRepository_GetByID_Call {
	return &DailyLoadMaterialRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *DailyLoadMaterialRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DailyLoadMaterialRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadMaterialRepository_GetByID_Call) Return(_a0 *planning.DailyLoadMaterial, _a1 error) *DailyLoadMaterialRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DailyLoadMaterialRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*planning.DailyLoadMaterial, error)) *DailyLoadMaterialRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPlan provides a mock function with given fields: ctx, planID
func (_m *DailyLoadMaterialRepository) ListByPlan(ctx context.Context, planID uuid.UUID) ([]planning.DailyLoadMaterial, error) {
	ret := _m.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for ListByPlan")
	}

	var r0 []planning.DailyLoadMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]planning.DailyLoadMaterial, error)); ok {
		return rf(ctx, planID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []planning.DailyLoadMaterial); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]planning.DailyLoadMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DailyLoadMaterialRepository_ListByPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPlan'
type DailyLoadMaterialRepository_ListByPlan_Call struct {
	*mock.Call
}

// ListByPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - planID uuid.UUID
func (_e *DailyLoadMaterialRepository_Expecter) ListByPlan(ctx interface{}, planID interface{}) *DailyLoadMaterialRepository_ListByPlan_Call {
	return &DailyLoadMaterialRepository_ListByPlan_Call{Call: _e.mock.On("ListByPlan", ctx, planID)}
}

func (_c *DailyLoadMaterialRepository_ListByPlan_Call) Run(run func(ctx context.Context, planID uuid.UUID)) *DailyLoadMaterialRepository_ListByPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DailyLoadMaterialRepository_ListByPlan_Call) Return(_a0 []planning.DailyLoadMaterial, _a1 error) *DailyLoadMaterialRepository_ListByPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DailyLoadMaterialRepository_ListByPlan_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]planning.DailyLoadMaterial, error)) *DailyLoadMaterialRepository_ListByPlan_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *DailyLoadMaterialRepository) Update(ctx context.Context, id uuid.UUID, m *planning.DailyLoadMaterial) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *planning.DailyLoadMaterial) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DailyLoadMaterialRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DailyLoadMaterialRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - m *planning.DailyLoadMaterial
func (_e *DailyLoadMaterialRepository_Expecter) Update(ctx interface{}, id interface{}, m interface{}) *DailyLoadMaterialRepository_Update_Call {
	return &DailyLoadMaterialRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, m)}
}

func (_c *DailyLoadMaterialRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, m *planning.DailyLoadMaterial)) *DailyLoadMaterialRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*planning.DailyLoadMaterial))
	})
	return _c
}

func (_c *DailyLoadMaterialRepository_Update_Call) Return(_a0 error) *DailyLoadMaterialRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DailyLoadMaterialRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *planning.DailyLoadMaterial) error) *DailyLoadMaterialRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDailyLoadMaterialRepository creates a new instance of DailyLoadMaterialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDailyLoadMaterialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DailyLoadMaterialRepository {
	mock := &DailyLoadMaterialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
