// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// EPPItemRepository is an autogenerated mock type for the EPPItemRepository type
type EPPItemRepository struct {
	mock.Mock
}

type EPPItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EPPItemRepository) EXPECT() *EPPItemRepository_Expecter {
	return &EPPItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *EPPItemRepository) Create(ctx context.Context, item *inventory.EPPItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.EPPItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EPPItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EPPItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *inventory.EPPItem
func (_e *EPPItemRepository_Expecter) Create(ctx interface{}, item interface{}) *EPPItemRepository_Create_Call {
	return &EPPItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *EPPItemRepository_Create_Call) Run(run func(ctx context.Context, item *inventory.EPPItem)) *EPPItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.EPPItem))
	})
	return _c
}

func (_c *EPPItemRepository_Create_Call) Return(_a0 error) *EPPItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EPPItemRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.EPPItem) error) *EPPItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *EPPItemRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EPPItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EPPItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *EPPItemRepository_Expecter) Delete(ctx interface{}, id interface{}) *EPPItemRepository_Delete_Call {
	return &EPPItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *EPPItemRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *EPPItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *EPPItemRepository_Delete_Call) Return(_a0 error) *EPPItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EPPItemRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *EPPItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *EPPItemRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.EPPItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.EPPItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.EPPItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.EPPItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.EPPItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EPPItemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type EPPItemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *EPPItemRepository_Expecter) GetByID(ctx interface{}, id interface{}) *EPPItemRepository_GetByID_Call {
	return &EPPItemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *EPPItemRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *EPPItemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *EPPItemRepository_GetByID_Call) Return(_a0 *inventory.EPPItem, _a1 error) *EPPItemRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EPPItemRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.EPPItem, error)) *EPPItemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *EPPItemRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.EPPItem], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.EPPItem]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.EPPItem], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.EPPItem]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.EPPItem])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EPPItemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type EPPItemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *EPPItemRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *EPPItemRepository_List_Call {
	return &EPPItemRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *EPPItemRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *EPPItemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *EPPItemRepository_List_Call) Return(_a0 *repository.ListResult[inventory.EPPItem], _a1 error) *EPPItemRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EPPItemRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.EPPItem], error)) *EPPItemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *EPPItemRepository) Update(ctx context.Context, id uuid.UUID, item *inventory.EPPItem) error {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.EPPItem) error); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EPPItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EPPItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - item *inventory.EPPItem
func (_e *EPPItemRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *EPPItemRepository_Update_Call {
	return &EPPItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *EPPItemRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, item *inventory.EPPItem)) *EPPItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.EPPItem))
	})
	return _c
}

func (_c *EPPItemRepository_Update_Call) Return(_a0 error) *EPPItemRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EPPItemRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.EPPItem) error) *EPPItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewEPPItemRepository creates a new instance of EPPItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEPPItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EPPItemRepository {
	mock := &EPPItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
