// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	geocoding "localis-backend/internal/model/geocoding"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// GeocodingAddressRepository is an autogenerated mock type for the GeocodingAddressRepository type
type GeocodingAddressRepository struct {
	mock.Mock
}

type GeocodingAddressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GeocodingAddressRepository) EXPECT() *GeocodingAddressRepository_Expecter {
	return &GeocodingAddressRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, addr
func (_m *GeocodingAddressRepository) Create(ctx context.Context, addr *geocoding.Address) error {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *geocoding.Address) error); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeocodingAddressRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GeocodingAddressRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - addr *geocoding.Address
func (_e *GeocodingAddressRepository_Expecter) Create(ctx interface{}, addr interface{}) *GeocodingAddressRepository_Create_Call {
	return &GeocodingAddressRepository_Create_Call{Call: _e.mock.On("Create", ctx, addr)}
}

func (_c *GeocodingAddressRepository_Create_Call) Run(run func(ctx context.Context, addr *geocoding.Address)) *GeocodingAddressRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*geocoding.Address))
	})
	return _c
}

func (_c *GeocodingAddressRepository_Create_Call) Return(_a0 error) *GeocodingAddressRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GeocodingAddressRepository_Create_Call) RunAndReturn(run func(context.Context, *geocoding.Address) error) *GeocodingAddressRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *GeocodingAddressRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeocodingAddressRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GeocodingAddressRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GeocodingAddressRepository_Expecter) Delete(ctx interface{}, id interface{}) *GeocodingAddressRepository_Delete_Call {
	return &GeocodingAddressRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *GeocodingAddressRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GeocodingAddressRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GeocodingAddressRepository_Delete_Call) Return(_a0 error) *GeocodingAddressRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GeocodingAddressRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *GeocodingAddressRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindNearby provides a mock function with given fields: ctx, lat, lng, radiusMeters
func (_m *GeocodingAddressRepository) FindNearby(ctx context.Context, lat float64, lng float64, radiusMeters float64) ([]geocoding.Address, error) {
	ret := _m.Called(ctx, lat, lng, radiusMeters)

	if len(ret) == 0 {
		panic("no return value specified for FindNearby")
	}

	var r0 []geocoding.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64) ([]geocoding.Address, error)); ok {
		return rf(ctx, lat, lng, radiusMeters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64) []geocoding.Address); ok {
		r0 = rf(ctx, lat, lng, radiusMeters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]geocoding.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64) error); ok {
		r1 = rf(ctx, lat, lng, radiusMeters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeocodingAddressRepository_FindNearby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNearby'
type GeocodingAddressRepository_FindNearby_Call struct {
	*mock.Call
}

// FindNearby is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
//   - radiusMeters float64
func (_e *GeocodingAddressRepository_Expecter) FindNearby(ctx interface{}, lat interface{}, lng interface{}, radiusMeters interface{}) *GeocodingAddressRepository_FindNearby_Call {
	return &GeocodingAddressRepository_FindNearby_Call{Call: _e.mock.On("FindNearby", ctx, lat, lng, radiusMeters)}
}

func (_c *GeocodingAddressRepository_FindNearby_Call) Run(run func(ctx context.Context, lat float64, lng float64, radiusMeters float64)) *GeocodingAddressRepository_FindNearby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64))
	})
	return _c
}

func (_c *GeocodingAddressRepository_FindNearby_Call) Return(_a0 []geocoding.Address, _a1 error) *GeocodingAddressRepository_FindNearby_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeocodingAddressRepository_FindNearby_Call) RunAndReturn(run func(context.Context, float64, float64, float64) ([]geocoding.Address, error)) *GeocodingAddressRepository_FindNearby_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GeocodingAddressRepository) GetByID(ctx context.Context, id uuid.UUID) (*geocoding.Address, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *geocoding.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*geocoding.Address, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *geocoding.Address); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*geocoding.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeocodingAddressRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GeocodingAddressRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GeocodingAddressRepository_Expecter) GetByID(ctx interface{}, id interface{}) *GeocodingAddressRepository_GetByID_Call {
	return &GeocodingAddressRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GeocodingAddressRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GeocodingAddressRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GeocodingAddressRepository_GetByID_Call) Return(_a0 *geocoding.Address, _a1 error) *GeocodingAddressRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeocodingAddressRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*geocoding.Address, error)) *GeocodingAddressRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *GeocodingAddressRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[geocoding.Address], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[geocoding.Address]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[geocoding.Address], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[geocoding.Address]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[geocoding.Address])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeocodingAddressRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type GeocodingAddressRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *GeocodingAddressRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *GeocodingAddressRepository_List_Call {
	return &GeocodingAddressRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *GeocodingAddressRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *GeocodingAddressRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *GeocodingAddressRepository_List_Call) Return(_a0 *repository.ListResult[geocoding.Address], _a1 error) *GeocodingAddressRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeocodingAddressRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[geocoding.Address], error)) *GeocodingAddressRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, addr
func (_m *GeocodingAddressRepository) Update(ctx context.Context, id uuid.UUID, addr *geocoding.Address) error {
	ret := _m.Called(ctx, id, addr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *geocoding.Address) error); ok {
		r0 = rf(ctx, id, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeocodingAddressRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GeocodingAddressRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - addr *geocoding.Address
func (_e *GeocodingAddressRepository_Expecter) Update(ctx interface{}, id interface{}, addr interface{}) *GeocodingAddressRepository_Update_Call {
	return &GeocodingAddressRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, addr)}
}

func (_c *GeocodingAddressRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, addr *geocoding.Address)) *GeocodingAddressRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*geocoding.Address))
	})
	return _c
}

func (_c *GeocodingAddressRepository_Update_Call) Return(_a0 error) *GeocodingAddressRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GeocodingAddressRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *geocoding.Address) error) *GeocodingAddressRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGeocodingAddressRepository creates a new instance of GeocodingAddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeocodingAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeocodingAddressRepository {
	mock := &GeocodingAddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
