// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// MaintenanceRecordRepository is an autogenerated mock type for the MaintenanceRecordRepository type
type MaintenanceRecordRepository struct {
	mock.Mock
}

type MaintenanceRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MaintenanceRecordRepository) EXPECT() *MaintenanceRecordRepository_Expecter {
	return &MaintenanceRecordRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rec
func (_m *MaintenanceRecordRepository) Create(ctx context.Context, rec *inventory.MaintenanceRecord) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.MaintenanceRecord) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceRecordRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MaintenanceRecordRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rec *inventory.MaintenanceRecord
func (_e *MaintenanceRecordRepository_Expecter) Create(ctx interface{}, rec interface{}) *MaintenanceRecordRepository_Create_Call {
	return &MaintenanceRecordRepository_Create_Call{Call: _e.mock.On("Create", ctx, rec)}
}

func (_c *MaintenanceRecordRepository_Create_Call) Run(run func(ctx context.Context, rec *inventory.MaintenanceRecord)) *MaintenanceRecordRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.MaintenanceRecord))
	})
	return _c
}

func (_c *MaintenanceRecordRepository_Create_Call) Return(_a0 error) *MaintenanceRecordRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceRecordRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.MaintenanceRecord) error) *MaintenanceRecordRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MaintenanceRecordRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceRecordRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MaintenanceRecordRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MaintenanceRecordRepository_Expecter) Delete(ctx interface{}, id interface{}) *MaintenanceRecordRepository_Delete_Call {
	return &MaintenanceRecordRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MaintenanceRecordRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MaintenanceRecordRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MaintenanceRecordRepository_Delete_Call) Return(_a0 error) *MaintenanceRecordRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceRecordRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MaintenanceRecordRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MaintenanceRecordRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.MaintenanceRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.MaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.MaintenanceRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.MaintenanceRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.MaintenanceRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceRecordRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MaintenanceRecordRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MaintenanceRecordRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MaintenanceRecordRepository_GetByID_Call {
	return &MaintenanceRecordRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MaintenanceRecordRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MaintenanceRecordRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MaintenanceRecordRepository_GetByID_Call) Return(_a0 *inventory.MaintenanceRecord, _a1 error) *MaintenanceRecordRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceRecordRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.MaintenanceRecord, error)) *MaintenanceRecordRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MaintenanceRecordRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.MaintenanceRecord], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.MaintenanceRecord]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.MaintenanceRecord], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.MaintenanceRecord]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.MaintenanceRecord])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceRecordRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MaintenanceRecordRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MaintenanceRecordRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MaintenanceRecordRepository_List_Call {
	return &MaintenanceRecordRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MaintenanceRecordRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MaintenanceRecordRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MaintenanceRecordRepository_List_Call) Return(_a0 *repository.ListResult[inventory.MaintenanceRecord], _a1 error) *MaintenanceRecordRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceRecordRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.MaintenanceRecord], error)) *MaintenanceRecordRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, rec
func (_m *MaintenanceRecordRepository) Update(ctx context.Context, id uuid.UUID, rec *inventory.MaintenanceRecord) error {
	ret := _m.Called(ctx, id, rec)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.MaintenanceRecord) error); ok {
		r0 = rf(ctx, id, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceRecordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MaintenanceRecordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - rec *inventory.MaintenanceRecord
func (_e *MaintenanceRecordRepository_Expecter) Update(ctx interface{}, id interface{}, rec interface{}) *MaintenanceRecordRepository_Update_Call {
	return &MaintenanceRecordRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, rec)}
}

func (_c *MaintenanceRecordRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, rec *inventory.MaintenanceRecord)) *MaintenanceRecordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.MaintenanceRecord))
	})
	return _c
}

func (_c *MaintenanceRecordRepository_Update_Call) Return(_a0 error) *MaintenanceRecordRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceRecordRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.MaintenanceRecord) error) *MaintenanceRecordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMaintenanceRecordRepository creates a new instance of MaintenanceRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceRecordRepository {
	mock := &MaintenanceRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
