// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// MaintenanceScheduleRepository is an autogenerated mock type for the MaintenanceScheduleRepository type
type MaintenanceScheduleRepository struct {
	mock.Mock
}

type MaintenanceScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MaintenanceScheduleRepository) EXPECT() *MaintenanceScheduleRepository_Expecter {
	return &MaintenanceScheduleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sched
func (_m *MaintenanceScheduleRepository) Create(ctx context.Context, sched *inventory.MaintenanceSchedule) error {
	ret := _m.Called(ctx, sched)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.MaintenanceSchedule) error); ok {
		r0 = rf(ctx, sched)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceScheduleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MaintenanceScheduleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sched *inventory.MaintenanceSchedule
func (_e *MaintenanceScheduleRepository_Expecter) Create(ctx interface{}, sched interface{}) *MaintenanceScheduleRepository_Create_Call {
	return &MaintenanceScheduleRepository_Create_Call{Call: _e.mock.On("Create", ctx, sched)}
}

func (_c *MaintenanceScheduleRepository_Create_Call) Run(run func(ctx context.Context, sched *inventory.MaintenanceSchedule)) *MaintenanceScheduleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.MaintenanceSchedule))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_Create_Call) Return(_a0 error) *MaintenanceScheduleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceScheduleRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.MaintenanceSchedule) error) *MaintenanceScheduleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MaintenanceScheduleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceScheduleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MaintenanceScheduleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MaintenanceScheduleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MaintenanceScheduleRepository_Delete_Call {
	return &MaintenanceScheduleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MaintenanceScheduleRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MaintenanceScheduleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_Delete_Call) Return(_a0 error) *MaintenanceScheduleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceScheduleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MaintenanceScheduleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MaintenanceScheduleRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.MaintenanceSchedule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.MaintenanceSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.MaintenanceSchedule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.MaintenanceSchedule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.MaintenanceSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceScheduleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MaintenanceScheduleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MaintenanceScheduleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MaintenanceScheduleRepository_GetByID_Call {
	return &MaintenanceScheduleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MaintenanceScheduleRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MaintenanceScheduleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_GetByID_Call) Return(_a0 *inventory.MaintenanceSchedule, _a1 error) *MaintenanceScheduleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceScheduleRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.MaintenanceSchedule, error)) *MaintenanceScheduleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MaintenanceScheduleRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.MaintenanceSchedule], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.MaintenanceSchedule]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.MaintenanceSchedule], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.MaintenanceSchedule]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.MaintenanceSchedule])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceScheduleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MaintenanceScheduleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MaintenanceScheduleRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MaintenanceScheduleRepository_List_Call {
	return &MaintenanceScheduleRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MaintenanceScheduleRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MaintenanceScheduleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_List_Call) Return(_a0 *repository.ListResult[inventory.MaintenanceSchedule], _a1 error) *MaintenanceScheduleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceScheduleRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.MaintenanceSchedule], error)) *MaintenanceScheduleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx
func (_m *MaintenanceScheduleRepository) ListActive(ctx context.Context) ([]inventory.MaintenanceSchedule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []inventory.MaintenanceSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]inventory.MaintenanceSchedule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []inventory.MaintenanceSchedule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inventory.MaintenanceSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceScheduleRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MaintenanceScheduleRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MaintenanceScheduleRepository_Expecter) ListActive(ctx interface{}) *MaintenanceScheduleRepository_ListActive_Call {
	return &MaintenanceScheduleRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MaintenanceScheduleRepository_ListActive_Call) Run(run func(ctx context.Context)) *MaintenanceScheduleRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_ListActive_Call) Return(_a0 []inventory.MaintenanceSchedule, _a1 error) *MaintenanceScheduleRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceScheduleRepository_ListActive_Call) RunAndReturn(run func(context.Context) ([]inventory.MaintenanceSchedule, error)) *MaintenanceScheduleRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, sched
func (_m *MaintenanceScheduleRepository) Update(ctx context.Context, id uuid.UUID, sched *inventory.MaintenanceSchedule) error {
	ret := _m.Called(ctx, id, sched)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.MaintenanceSchedule) error); ok {
		r0 = rf(ctx, id, sched)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceScheduleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MaintenanceScheduleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - sched *inventory.MaintenanceSchedule
func (_e *MaintenanceScheduleRepository_Expecter) Update(ctx interface{}, id interface{}, sched interface{}) *MaintenanceScheduleRepository_Update_Call {
	return &MaintenanceScheduleRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, sched)}
}

func (_c *MaintenanceScheduleRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, sched *inventory.MaintenanceSchedule)) *MaintenanceScheduleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.MaintenanceSchedule))
	})
	return _c
}

func (_c *MaintenanceScheduleRepository_Update_Call) Return(_a0 error) *MaintenanceScheduleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceScheduleRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.MaintenanceSchedule) error) *MaintenanceScheduleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMaintenanceScheduleRepository creates a new instance of MaintenanceScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceScheduleRepository {
	mock := &MaintenanceScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
