// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	notifications "localis-backend/internal/model/notifications"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

type NotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepository) EXPECT() *NotificationRepository_Expecter {
	return &NotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, notif
func (_m *NotificationRepository) Create(ctx context.Context, notif *notifications.Notification) error {
	ret := _m.Called(ctx, notif)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.Notification) error); ok {
		r0 = rf(ctx, notif)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - notif *notifications.Notification
func (_e *NotificationRepository_Expecter) Create(ctx interface{}, notif interface{}) *NotificationRepository_Create_Call {
	return &NotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, notif)}
}

func (_c *NotificationRepository_Create_Call) Run(run func(ctx context.Context, notif *notifications.Notification)) *NotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notifications.Notification))
	})
	return _c
}

func (_c *NotificationRepository_Create_Call) Return(_a0 error) *NotificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *notifications.Notification) error) *NotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NotificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *NotificationRepository_Expecter) Delete(ctx interface{}, id interface{}) *NotificationRepository_Delete_Call {
	return &NotificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *NotificationRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *NotificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *NotificationRepository_Delete_Call) Return(_a0 error) *NotificationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *NotificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) GetByID(ctx context.Context, id uuid.UUID) (*notifications.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*notifications.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *notifications.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type NotificationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *NotificationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *NotificationRepository_GetByID_Call {
	return &NotificationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *NotificationRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *NotificationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *NotificationRepository_GetByID_Call) Return(_a0 *notifications.Notification, _a1 error) *NotificationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*notifications.Notification, error)) *NotificationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *NotificationRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[notifications.Notification], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[notifications.Notification]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[notifications.Notification], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[notifications.Notification]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[notifications.Notification])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *NotificationRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *NotificationRepository_List_Call {
	return &NotificationRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *NotificationRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *NotificationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *NotificationRepository_List_Call) Return(_a0 *repository.ListResult[notifications.Notification], _a1 error) *NotificationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[notifications.Notification], error)) *NotificationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, notif
func (_m *NotificationRepository) Update(ctx context.Context, id uuid.UUID, notif *notifications.Notification) error {
	ret := _m.Called(ctx, id, notif)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *notifications.Notification) error); ok {
		r0 = rf(ctx, id, notif)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NotificationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - notif *notifications.Notification
func (_e *NotificationRepository_Expecter) Update(ctx interface{}, id interface{}, notif interface{}) *NotificationRepository_Update_Call {
	return &NotificationRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, notif)}
}

func (_c *NotificationRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, notif *notifications.Notification)) *NotificationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*notifications.Notification))
	})
	return _c
}

func (_c *NotificationRepository_Update_Call) Return(_a0 error) *NotificationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *notifications.Notification) error) *NotificationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
