// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	notifications "localis-backend/internal/model/notifications"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// NotificationTemplateRepository is an autogenerated mock type for the NotificationTemplateRepository type
type NotificationTemplateRepository struct {
	mock.Mock
}

type NotificationTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationTemplateRepository) EXPECT() *NotificationTemplateRepository_Expecter {
	return &NotificationTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tmpl
func (_m *NotificationTemplateRepository) Create(ctx context.Context, tmpl *notifications.NotificationTemplate) error {
	ret := _m.Called(ctx, tmpl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.NotificationTemplate) error); ok {
		r0 = rf(ctx, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tmpl *notifications.NotificationTemplate
func (_e *NotificationTemplateRepository_Expecter) Create(ctx interface{}, tmpl interface{}) *NotificationTemplateRepository_Create_Call {
	return &NotificationTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, tmpl)}
}

func (_c *NotificationTemplateRepository_Create_Call) Run(run func(ctx context.Context, tmpl *notifications.NotificationTemplate)) *NotificationTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notifications.NotificationTemplate))
	})
	return _c
}

func (_c *NotificationTemplateRepository_Create_Call) Return(_a0 error) *NotificationTemplateRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationTemplateRepository_Create_Call) RunAndReturn(run func(context.Context, *notifications.NotificationTemplate) error) *NotificationTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *NotificationTemplateRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NotificationTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *NotificationTemplateRepository_Expecter) Delete(ctx interface{}, id interface{}) *NotificationTemplateRepository_Delete_Call {
	return &NotificationTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *NotificationTemplateRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *NotificationTemplateRepository_Delete_Call) Return(_a0 error) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationTemplateRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *NotificationTemplateRepository) GetByID(ctx context.Context, id uuid.UUID) (*notifications.NotificationTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *notifications.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*notifications.NotificationTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *notifications.NotificationTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type NotificationTemplateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *NotificationTemplateRepository_Expecter) GetByID(ctx interface{}, id interface{}) *NotificationTemplateRepository_GetByID_Call {
	return &NotificationTemplateRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *NotificationTemplateRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *NotificationTemplateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *NotificationTemplateRepository_GetByID_Call) Return(_a0 *notifications.NotificationTemplate, _a1 error) *NotificationTemplateRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*notifications.NotificationTemplate, error)) *NotificationTemplateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *NotificationTemplateRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[notifications.NotificationTemplate], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[notifications.NotificationTemplate]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[notifications.NotificationTemplate], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[notifications.NotificationTemplate]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[notifications.NotificationTemplate])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationTemplateRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *NotificationTemplateRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *NotificationTemplateRepository_List_Call {
	return &NotificationTemplateRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *NotificationTemplateRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *NotificationTemplateRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *NotificationTemplateRepository_List_Call) Return(_a0 *repository.ListResult[notifications.NotificationTemplate], _a1 error) *NotificationTemplateRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[notifications.NotificationTemplate], error)) *NotificationTemplateRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, tmpl
func (_m *NotificationTemplateRepository) Update(ctx context.Context, id uuid.UUID, tmpl *notifications.NotificationTemplate) error {
	ret := _m.Called(ctx, id, tmpl)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *notifications.NotificationTemplate) error); ok {
		r0 = rf(ctx, id, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NotificationTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tmpl *notifications.NotificationTemplate
func (_e *NotificationTemplateRepository_Expecter) Update(ctx interface{}, id interface{}, tmpl interface{}) *NotificationTemplateRepository_Update_Call {
	return &NotificationTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, tmpl)}
}

func (_c *NotificationTemplateRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, tmpl *notifications.NotificationTemplate)) *NotificationTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*notifications.NotificationTemplate))
	})
	return _c
}

func (_c *NotificationTemplateRepository_Update_Call) Return(_a0 error) *NotificationTemplateRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationTemplateRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *notifications.NotificationTemplate) error) *NotificationTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationTemplateRepository creates a new instance of NotificationTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationTemplateRepository {
	mock := &NotificationTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
