// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartnerAgreementRepository is an autogenerated mock type for the PartnerAgreementRepository type
type PartnerAgreementRepository struct {
	mock.Mock
}

type PartnerAgreementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartnerAgreementRepository) EXPECT() *PartnerAgreementRepository_Expecter {
	return &PartnerAgreementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, agreement
func (_m *PartnerAgreementRepository) Create(ctx context.Context, agreement *partners.PartnerAgreement) error {
	ret := _m.Called(ctx, agreement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.PartnerAgreement) error); ok {
		r0 = rf(ctx, agreement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PartnerAgreementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - agreement *partners.PartnerAgreement
func (_e *PartnerAgreementRepository_Expecter) Create(ctx interface{}, agreement interface{}) *PartnerAgreementRepository_Create_Call {
	return &PartnerAgreementRepository_Create_Call{Call: _e.mock.On("Create", ctx, agreement)}
}

func (_c *PartnerAgreementRepository_Create_Call) Run(run func(ctx context.Context, agreement *partners.PartnerAgreement)) *PartnerAgreementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.PartnerAgreement))
	})
	return _c
}

func (_c *PartnerAgreementRepository_Create_Call) Return(_a0 error) *PartnerAgreementRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementRepository_Create_Call) RunAndReturn(run func(context.Context, *partners.PartnerAgreement) error) *PartnerAgreementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PartnerAgreementRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementRepository_Expecter) Delete(ctx interface{}, id interface{}) *PartnerAgreementRepository_Delete_Call {
	return &PartnerAgreementRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PartnerAgreementRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementRepository_Delete_Call) Return(_a0 error) *PartnerAgreementRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PartnerAgreementRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementRepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.PartnerAgreement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.PartnerAgreement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.PartnerAgreement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.PartnerAgreement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.PartnerAgreement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PartnerAgreementRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PartnerAgreementRepository_GetByID_Call {
	return &PartnerAgreementRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PartnerAgreementRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementRepository_GetByID_Call) Return(_a0 *partners.PartnerAgreement, _a1 error) *PartnerAgreementRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.PartnerAgreement, error)) *PartnerAgreementRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPartner provides a mock function with given fields: ctx, partnerID
func (_m *PartnerAgreementRepository) ListByPartner(ctx context.Context, partnerID uuid.UUID) ([]partners.PartnerAgreement, error) {
	ret := _m.Called(ctx, partnerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByPartner")
	}

	var r0 []partners.PartnerAgreement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]partners.PartnerAgreement, error)); ok {
		return rf(ctx, partnerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []partners.PartnerAgreement); ok {
		r0 = rf(ctx, partnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]partners.PartnerAgreement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, partnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementRepository_ListByPartner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPartner'
type PartnerAgreementRepository_ListByPartner_Call struct {
	*mock.Call
}

// ListByPartner is a helper method to define mock.On call
//   - ctx context.Context
//   - partnerID uuid.UUID
func (_e *PartnerAgreementRepository_Expecter) ListByPartner(ctx interface{}, partnerID interface{}) *PartnerAgreementRepository_ListByPartner_Call {
	return &PartnerAgreementRepository_ListByPartner_Call{Call: _e.mock.On("ListByPartner", ctx, partnerID)}
}

func (_c *PartnerAgreementRepository_ListByPartner_Call) Run(run func(ctx context.Context, partnerID uuid.UUID)) *PartnerAgreementRepository_ListByPartner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementRepository_ListByPartner_Call) Return(_a0 []partners.PartnerAgreement, _a1 error) *PartnerAgreementRepository_ListByPartner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementRepository_ListByPartner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]partners.PartnerAgreement, error)) *PartnerAgreementRepository_ListByPartner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, agreement
func (_m *PartnerAgreementRepository) Update(ctx context.Context, id uuid.UUID, agreement *partners.PartnerAgreement) error {
	ret := _m.Called(ctx, id, agreement)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *partners.PartnerAgreement) error); ok {
		r0 = rf(ctx, id, agreement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PartnerAgreementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - agreement *partners.PartnerAgreement
func (_e *PartnerAgreementRepository_Expecter) Update(ctx interface{}, id interface{}, agreement interface{}) *PartnerAgreementRepository_Update_Call {
	return &PartnerAgreementRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, agreement)}
}

func (_c *PartnerAgreementRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, agreement *partners.PartnerAgreement)) *PartnerAgreementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*partners.PartnerAgreement))
	})
	return _c
}

func (_c *PartnerAgreementRepository_Update_Call) Return(_a0 error) *PartnerAgreementRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *partners.PartnerAgreement) error) *PartnerAgreementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartnerAgreementRepository creates a new instance of PartnerAgreementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerAgreementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerAgreementRepository {
	mock := &PartnerAgreementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
