// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartnerAgreementFormRepository is an autogenerated mock type for the PartnerAgreementFormRepository type
type PartnerAgreementFormRepository struct {
	mock.Mock
}

type PartnerAgreementFormRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartnerAgreementFormRepository) EXPECT() *PartnerAgreementFormRepository_Expecter {
	return &PartnerAgreementFormRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, form
func (_m *PartnerAgreementFormRepository) Create(ctx context.Context, form *partners.PartnerAgreementForm) error {
	ret := _m.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.PartnerAgreementForm) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementFormRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PartnerAgreementFormRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - form *partners.PartnerAgreementForm
func (_e *PartnerAgreementFormRepository_Expecter) Create(ctx interface{}, form interface{}) *PartnerAgreementFormRepository_Create_Call {
	return &PartnerAgreementFormRepository_Create_Call{Call: _e.mock.On("Create", ctx, form)}
}

func (_c *PartnerAgreementFormRepository_Create_Call) Run(run func(ctx context.Context, form *partners.PartnerAgreementForm)) *PartnerAgreementFormRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.PartnerAgreementForm))
	})
	return _c
}

func (_c *PartnerAgreementFormRepository_Create_Call) Return(_a0 error) *PartnerAgreementFormRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementFormRepository_Create_Call) RunAndReturn(run func(context.Context, *partners.PartnerAgreementForm) error) *PartnerAgreementFormRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementFormRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementFormRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PartnerAgreementFormRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementFormRepository_Expecter) Delete(ctx interface{}, id interface{}) *PartnerAgreementFormRepository_Delete_Call {
	return &PartnerAgreementFormRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PartnerAgreementFormRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementFormRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementFormRepository_Delete_Call) Return(_a0 error) *PartnerAgreementFormRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementFormRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PartnerAgreementFormRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementFormRepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.PartnerAgreementForm, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.PartnerAgreementForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.PartnerAgreementForm, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.PartnerAgreementForm); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.PartnerAgreementForm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementFormRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PartnerAgreementFormRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementFormRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PartnerAgreementFormRepository_GetByID_Call {
	return &PartnerAgreementFormRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PartnerAgreementFormRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementFormRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementFormRepository_GetByID_Call) Return(_a0 *partners.PartnerAgreementForm, _a1 error) *PartnerAgreementFormRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementFormRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.PartnerAgreementForm, error)) *PartnerAgreementFormRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByAgreement provides a mock function with given fields: ctx, agreementID
func (_m *PartnerAgreementFormRepository) ListByAgreement(ctx context.Context, agreementID uuid.UUID) ([]partners.PartnerAgreementForm, error) {
	ret := _m.Called(ctx, agreementID)

	if len(ret) == 0 {
		panic("no return value specified for ListByAgreement")
	}

	var r0 []partners.PartnerAgreementForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]partners.PartnerAgreementForm, error)); ok {
		return rf(ctx, agreementID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []partners.PartnerAgreementForm); ok {
		r0 = rf(ctx, agreementID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]partners.PartnerAgreementForm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, agreementID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementFormRepository_ListByAgreement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByAgreement'
type PartnerAgreementFormRepository_ListByAgreement_Call struct {
	*mock.Call
}

// ListByAgreement is a helper method to define mock.On call
//   - ctx context.Context
//   - agreementID uuid.UUID
func (_e *PartnerAgreementFormRepository_Expecter) ListByAgreement(ctx interface{}, agreementID interface{}) *PartnerAgreementFormRepository_ListByAgreement_Call {
	return &PartnerAgreementFormRepository_ListByAgreement_Call{Call: _e.mock.On("ListByAgreement", ctx, agreementID)}
}

func (_c *PartnerAgreementFormRepository_ListByAgreement_Call) Run(run func(ctx context.Context, agreementID uuid.UUID)) *PartnerAgreementFormRepository_ListByAgreement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementFormRepository_ListByAgreement_Call) Return(_a0 []partners.PartnerAgreementForm, _a1 error) *PartnerAgreementFormRepository_ListByAgreement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementFormRepository_ListByAgreement_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]partners.PartnerAgreementForm, error)) *PartnerAgreementFormRepository_ListByAgreement_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartnerAgreementFormRepository creates a new instance of PartnerAgreementFormRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerAgreementFormRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerAgreementFormRepository {
	mock := &PartnerAgreementFormRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
