// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartnerAgreementDocRepository is an autogenerated mock type for the PartnerAgreementDocRepository type
type PartnerAgreementDocRepository struct {
	mock.Mock
}

type PartnerAgreementDocRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartnerAgreementDocRepository) EXPECT() *PartnerAgreementDocRepository_Expecter {
	return &PartnerAgreementDocRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, doc
func (_m *PartnerAgreementDocRepository) Create(ctx context.Context, doc *partners.PartnerAgreementDoc) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.PartnerAgreementDoc) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementDocRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PartnerAgreementDocRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *partners.PartnerAgreementDoc
func (_e *PartnerAgreementDocRepository_Expecter) Create(ctx interface{}, doc interface{}) *PartnerAgreementDocRepository_Create_Call {
	return &PartnerAgreementDocRepository_Create_Call{Call: _e.mock.On("Create", ctx, doc)}
}

func (_c *PartnerAgreementDocRepository_Create_Call) Run(run func(ctx context.Context, doc *partners.PartnerAgreementDoc)) *PartnerAgreementDocRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.PartnerAgreementDoc))
	})
	return _c
}

func (_c *PartnerAgreementDocRepository_Create_Call) Return(_a0 error) *PartnerAgreementDocRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementDocRepository_Create_Call) RunAndReturn(run func(context.Context, *partners.PartnerAgreementDoc) error) *PartnerAgreementDocRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementDocRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerAgreementDocRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PartnerAgreementDocRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementDocRepository_Expecter) Delete(ctx interface{}, id interface{}) *PartnerAgreementDocRepository_Delete_Call {
	return &PartnerAgreementDocRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PartnerAgreementDocRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementDocRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementDocRepository_Delete_Call) Return(_a0 error) *PartnerAgreementDocRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerAgreementDocRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PartnerAgreementDocRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PartnerAgreementDocRepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.PartnerAgreementDoc, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.PartnerAgreementDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.PartnerAgreementDoc, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.PartnerAgreementDoc); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.PartnerAgreementDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementDocRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PartnerAgreementDocRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerAgreementDocRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PartnerAgreementDocRepository_GetByID_Call {
	return &PartnerAgreementDocRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PartnerAgreementDocRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerAgreementDocRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementDocRepository_GetByID_Call) Return(_a0 *partners.PartnerAgreementDoc, _a1 error) *PartnerAgreementDocRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementDocRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.PartnerAgreementDoc, error)) *PartnerAgreementDocRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByAgreement provides a mock function with given fields: ctx, agreementID
func (_m *PartnerAgreementDocRepository) ListByAgreement(ctx context.Context, agreementID uuid.UUID) ([]partners.PartnerAgreementDoc, error) {
	ret := _m.Called(ctx, agreementID)

	if len(ret) == 0 {
		panic("no return value specified for ListByAgreement")
	}

	var r0 []partners.PartnerAgreementDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]partners.PartnerAgreementDoc, error)); ok {
		return rf(ctx, agreementID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []partners.PartnerAgreementDoc); ok {
		r0 = rf(ctx, agreementID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]partners.PartnerAgreementDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, agreementID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerAgreementDocRepository_ListByAgreement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByAgreement'
type PartnerAgreementDocRepository_ListByAgreement_Call struct {
	*mock.Call
}

// ListByAgreement is a helper method to define mock.On call
//   - ctx context.Context
//   - agreementID uuid.UUID
func (_e *PartnerAgreementDocRepository_Expecter) ListByAgreement(ctx interface{}, agreementID interface{}) *PartnerAgreementDocRepository_ListByAgreement_Call {
	return &PartnerAgreementDocRepository_ListByAgreement_Call{Call: _e.mock.On("ListByAgreement", ctx, agreementID)}
}

func (_c *PartnerAgreementDocRepository_ListByAgreement_Call) Run(run func(ctx context.Context, agreementID uuid.UUID)) *PartnerAgreementDocRepository_ListByAgreement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerAgreementDocRepository_ListByAgreement_Call) Return(_a0 []partners.PartnerAgreementDoc, _a1 error) *PartnerAgreementDocRepository_ListByAgreement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerAgreementDocRepository_ListByAgreement_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]partners.PartnerAgreementDoc, error)) *PartnerAgreementDocRepository_ListByAgreement_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartnerAgreementDocRepository creates a new instance of PartnerAgreementDocRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerAgreementDocRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerAgreementDocRepository {
	mock := &PartnerAgreementDocRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
