// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// PartnerRepository is an autogenerated mock type for the PartnerRepository type
type PartnerRepository struct {
	mock.Mock
}

type PartnerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartnerRepository) EXPECT() *PartnerRepository_Expecter {
	return &PartnerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, partner
func (_m *PartnerRepository) Create(ctx context.Context, partner *partners.Partner) error {
	ret := _m.Called(ctx, partner)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.Partner) error); ok {
		r0 = rf(ctx, partner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PartnerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - partner *partners.Partner
func (_e *PartnerRepository_Expecter) Create(ctx interface{}, partner interface{}) *PartnerRepository_Create_Call {
	return &PartnerRepository_Create_Call{Call: _e.mock.On("Create", ctx, partner)}
}

func (_c *PartnerRepository_Create_Call) Run(run func(ctx context.Context, partner *partners.Partner)) *PartnerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.Partner))
	})
	return _c
}

func (_c *PartnerRepository_Create_Call) Return(_a0 error) *PartnerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerRepository_Create_Call) RunAndReturn(run func(context.Context, *partners.Partner) error) *PartnerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PartnerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PartnerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerRepository_Expecter) Delete(ctx interface{}, id interface{}) *PartnerRepository_Delete_Call {
	return &PartnerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PartnerRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerRepository_Delete_Call) Return(_a0 error) *PartnerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PartnerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PartnerRepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.Partner, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.Partner, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.Partner); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PartnerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PartnerRepository_GetByID_Call {
	return &PartnerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PartnerRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerRepository_GetByID_Call) Return(_a0 *partners.Partner, _a1 error) *PartnerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.Partner, error)) *PartnerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *PartnerRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[partners.Partner], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[partners.Partner]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[partners.Partner], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[partners.Partner]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[partners.Partner])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartnerRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *PartnerRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *PartnerRepository_List_Call {
	return &PartnerRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *PartnerRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *PartnerRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *PartnerRepository_List_Call) Return(_a0 *repository.ListResult[partners.Partner], _a1 error) *PartnerRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[partners.Partner], error)) *PartnerRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, partner
func (_m *PartnerRepository) Update(ctx context.Context, id uuid.UUID, partner *partners.Partner) error {
	ret := _m.Called(ctx, id, partner)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *partners.Partner) error); ok {
		r0 = rf(ctx, id, partner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PartnerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - partner *partners.Partner
func (_e *PartnerRepository_Expecter) Update(ctx interface{}, id interface{}, partner interface{}) *PartnerRepository_Update_Call {
	return &PartnerRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, partner)}
}

func (_c *PartnerRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, partner *partners.Partner)) *PartnerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*partners.Partner))
	})
	return _c
}

func (_c *PartnerRepository_Update_Call) Return(_a0 error) *PartnerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *partners.Partner) error) *PartnerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartnerRepository creates a new instance of PartnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerRepository {
	mock := &PartnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
