// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartnerContactRepository is an autogenerated mock type for the PartnerContactRepository type
type PartnerContactRepository struct {
	mock.Mock
}

type PartnerContactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartnerContactRepository) EXPECT() *PartnerContactRepository_Expecter {
	return &PartnerContactRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, contact
func (_m *PartnerContactRepository) Create(ctx context.Context, contact *partners.PartnerContact) error {
	ret := _m.Called(ctx, contact)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.PartnerContact) error); ok {
		r0 = rf(ctx, contact)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerContactRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PartnerContactRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - contact *partners.PartnerContact
func (_e *PartnerContactRepository_Expecter) Create(ctx interface{}, contact interface{}) *PartnerContactRepository_Create_Call {
	return &PartnerContactRepository_Create_Call{Call: _e.mock.On("Create", ctx, contact)}
}

func (_c *PartnerContactRepository_Create_Call) Run(run func(ctx context.Context, contact *partners.PartnerContact)) *PartnerContactRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.PartnerContact))
	})
	return _c
}

func (_c *PartnerContactRepository_Create_Call) Return(_a0 error) *PartnerContactRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerContactRepository_Create_Call) RunAndReturn(run func(context.Context, *partners.PartnerContact) error) *PartnerContactRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PartnerContactRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerContactRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PartnerContactRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerContactRepository_Expecter) Delete(ctx interface{}, id interface{}) *PartnerContactRepository_Delete_Call {
	return &PartnerContactRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PartnerContactRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerContactRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerContactRepository_Delete_Call) Return(_a0 error) *PartnerContactRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerContactRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PartnerContactRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PartnerContactRepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.PartnerContact, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.PartnerContact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.PartnerContact, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.PartnerContact); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.PartnerContact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerContactRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PartnerContactRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartnerContactRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PartnerContactRepository_GetByID_Call {
	return &PartnerContactRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PartnerContactRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartnerContactRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerContactRepository_GetByID_Call) Return(_a0 *partners.PartnerContact, _a1 error) *PartnerContactRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerContactRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.PartnerContact, error)) *PartnerContactRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPartner provides a mock function with given fields: ctx, partnerID
func (_m *PartnerContactRepository) ListByPartner(ctx context.Context, partnerID uuid.UUID) ([]partners.PartnerContact, error) {
	ret := _m.Called(ctx, partnerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByPartner")
	}

	var r0 []partners.PartnerContact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]partners.PartnerContact, error)); ok {
		return rf(ctx, partnerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []partners.PartnerContact); ok {
		r0 = rf(ctx, partnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]partners.PartnerContact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, partnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartnerContactRepository_ListByPartner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPartner'
type PartnerContactRepository_ListByPartner_Call struct {
	*mock.Call
}

// ListByPartner is a helper method to define mock.On call
//   - ctx context.Context
//   - partnerID uuid.UUID
func (_e *PartnerContactRepository_Expecter) ListByPartner(ctx interface{}, partnerID interface{}) *PartnerContactRepository_ListByPartner_Call {
	return &PartnerContactRepository_ListByPartner_Call{Call: _e.mock.On("ListByPartner", ctx, partnerID)}
}

func (_c *PartnerContactRepository_ListByPartner_Call) Run(run func(ctx context.Context, partnerID uuid.UUID)) *PartnerContactRepository_ListByPartner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PartnerContactRepository_ListByPartner_Call) Return(_a0 []partners.PartnerContact, _a1 error) *PartnerContactRepository_ListByPartner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartnerContactRepository_ListByPartner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]partners.PartnerContact, error)) *PartnerContactRepository_ListByPartner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, contact
func (_m *PartnerContactRepository) Update(ctx context.Context, id uuid.UUID, contact *partners.PartnerContact) error {
	ret := _m.Called(ctx, id, contact)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *partners.PartnerContact) error); ok {
		r0 = rf(ctx, id, contact)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartnerContactRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PartnerContactRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - contact *partners.PartnerContact
func (_e *PartnerContactRepository_Expecter) Update(ctx interface{}, id interface{}, contact interface{}) *PartnerContactRepository_Update_Call {
	return &PartnerContactRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, contact)}
}

func (_c *PartnerContactRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, contact *partners.PartnerContact)) *PartnerContactRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*partners.PartnerContact))
	})
	return _c
}

func (_c *PartnerContactRepository_Update_Call) Return(_a0 error) *PartnerContactRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartnerContactRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *partners.PartnerContact) error) *PartnerContactRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartnerContactRepository creates a new instance of PartnerContactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartnerContactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartnerContactRepository {
	mock := &PartnerContactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
