// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	customers "localis-backend/internal/model/customers"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PropertyRepository is an autogenerated mock type for the PropertyRepository type
type PropertyRepository struct {
	mock.Mock
}

type PropertyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PropertyRepository) EXPECT() *PropertyRepository_Expecter {
	return &PropertyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, prop
func (_m *PropertyRepository) Create(ctx context.Context, prop *customers.Property) error {
	ret := _m.Called(ctx, prop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customers.Property) error); ok {
		r0 = rf(ctx, prop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PropertyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PropertyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - prop *customers.Property
func (_e *PropertyRepository_Expecter) Create(ctx interface{}, prop interface{}) *PropertyRepository_Create_Call {
	return &PropertyRepository_Create_Call{Call: _e.mock.On("Create", ctx, prop)}
}

func (_c *PropertyRepository_Create_Call) Run(run func(ctx context.Context, prop *customers.Property)) *PropertyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customers.Property))
	})
	return _c
}

func (_c *PropertyRepository_Create_Call) Return(_a0 error) *PropertyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PropertyRepository_Create_Call) RunAndReturn(run func(context.Context, *customers.Property) error) *PropertyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PropertyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PropertyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PropertyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PropertyRepository_Expecter) Delete(ctx interface{}, id interface{}) *PropertyRepository_Delete_Call {
	return &PropertyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PropertyRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PropertyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PropertyRepository_Delete_Call) Return(_a0 error) *PropertyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PropertyRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PropertyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PropertyRepository) GetByID(ctx context.Context, id uuid.UUID) (*customers.Property, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *customers.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customers.Property, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customers.Property); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PropertyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PropertyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PropertyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PropertyRepository_GetByID_Call {
	return &PropertyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PropertyRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PropertyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PropertyRepository_GetByID_Call) Return(_a0 *customers.Property, _a1 error) *PropertyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PropertyRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*customers.Property, error)) *PropertyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomerAddress provides a mock function with given fields: ctx, caID
func (_m *PropertyRepository) ListByCustomerAddress(ctx context.Context, caID uuid.UUID) ([]customers.Property, error) {
	ret := _m.Called(ctx, caID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomerAddress")
	}

	var r0 []customers.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]customers.Property, error)); ok {
		return rf(ctx, caID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []customers.Property); ok {
		r0 = rf(ctx, caID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customers.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, caID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PropertyRepository_ListByCustomerAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomerAddress'
type PropertyRepository_ListByCustomerAddress_Call struct {
	*mock.Call
}

// ListByCustomerAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - caID uuid.UUID
func (_e *PropertyRepository_Expecter) ListByCustomerAddress(ctx interface{}, caID interface{}) *PropertyRepository_ListByCustomerAddress_Call {
	return &PropertyRepository_ListByCustomerAddress_Call{Call: _e.mock.On("ListByCustomerAddress", ctx, caID)}
}

func (_c *PropertyRepository_ListByCustomerAddress_Call) Run(run func(ctx context.Context, caID uuid.UUID)) *PropertyRepository_ListByCustomerAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PropertyRepository_ListByCustomerAddress_Call) Return(_a0 []customers.Property, _a1 error) *PropertyRepository_ListByCustomerAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PropertyRepository_ListByCustomerAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]customers.Property, error)) *PropertyRepository_ListByCustomerAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, prop
func (_m *PropertyRepository) Update(ctx context.Context, id uuid.UUID, prop *customers.Property) error {
	ret := _m.Called(ctx, id, prop)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *customers.Property) error); ok {
		r0 = rf(ctx, id, prop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PropertyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PropertyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - prop *customers.Property
func (_e *PropertyRepository_Expecter) Update(ctx interface{}, id interface{}, prop interface{}) *PropertyRepository_Update_Call {
	return &PropertyRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, prop)}
}

func (_c *PropertyRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, prop *customers.Property)) *PropertyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*customers.Property))
	})
	return _c
}

func (_c *PropertyRepository_Update_Call) Return(_a0 error) *PropertyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PropertyRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *customers.Property) error) *PropertyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPropertyRepository creates a new instance of PropertyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyRepository {
	mock := &PropertyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
