// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// RentalRepository is an autogenerated mock type for the RentalRepository type
type RentalRepository struct {
	mock.Mock
}

type RentalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RentalRepository) EXPECT() *RentalRepository_Expecter {
	return &RentalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rental
func (_m *RentalRepository) Create(ctx context.Context, rental *inventory.Rental) error {
	ret := _m.Called(ctx, rental)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.Rental) error); ok {
		r0 = rf(ctx, rental)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RentalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RentalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rental *inventory.Rental
func (_e *RentalRepository_Expecter) Create(ctx interface{}, rental interface{}) *RentalRepository_Create_Call {
	return &RentalRepository_Create_Call{Call: _e.mock.On("Create", ctx, rental)}
}

func (_c *RentalRepository_Create_Call) Run(run func(ctx context.Context, rental *inventory.Rental)) *RentalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.Rental))
	})
	return _c
}

func (_c *RentalRepository_Create_Call) Return(_a0 error) *RentalRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RentalRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.Rental) error) *RentalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RentalRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RentalRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RentalRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RentalRepository_Expecter) Delete(ctx interface{}, id interface{}) *RentalRepository_Delete_Call {
	return &RentalRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RentalRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RentalRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *RentalRepository_Delete_Call) Return(_a0 error) *RentalRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RentalRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *RentalRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RentalRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.Rental, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.Rental
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.Rental, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.Rental); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.Rental)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RentalRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RentalRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RentalRepository_Expecter) GetByID(ctx interface{}, id interface{}) *RentalRepository_GetByID_Call {
	return &RentalRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RentalRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RentalRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *RentalRepository_GetByID_Call) Return(_a0 *inventory.Rental, _a1 error) *RentalRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RentalRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.Rental, error)) *RentalRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *RentalRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.Rental], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.Rental]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.Rental], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.Rental]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.Rental])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RentalRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RentalRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *RentalRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *RentalRepository_List_Call {
	return &RentalRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *RentalRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *RentalRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *RentalRepository_List_Call) Return(_a0 *repository.ListResult[inventory.Rental], _a1 error) *RentalRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RentalRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.Rental], error)) *RentalRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, rental
func (_m *RentalRepository) Update(ctx context.Context, id uuid.UUID, rental *inventory.Rental) error {
	ret := _m.Called(ctx, id, rental)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.Rental) error); ok {
		r0 = rf(ctx, id, rental)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RentalRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RentalRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - rental *inventory.Rental
func (_e *RentalRepository_Expecter) Update(ctx interface{}, id interface{}, rental interface{}) *RentalRepository_Update_Call {
	return &RentalRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, rental)}
}

func (_c *RentalRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, rental *inventory.Rental)) *RentalRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.Rental))
	})
	return _c
}

func (_c *RentalRepository_Update_Call) Return(_a0 error) *RentalRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RentalRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.Rental) error) *RentalRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRentalRepository creates a new instance of RentalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRentalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RentalRepository {
	mock := &RentalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
