// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ReportEntryRepository is an autogenerated mock type for the ReportEntryRepository type
type ReportEntryRepository struct {
	mock.Mock
}

type ReportEntryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportEntryRepository) EXPECT() *ReportEntryRepository_Expecter {
	return &ReportEntryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entry
func (_m *ReportEntryRepository) Create(ctx context.Context, entry *operations.ReportEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.ReportEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportEntryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportEntryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *operations.ReportEntry
func (_e *ReportEntryRepository_Expecter) Create(ctx interface{}, entry interface{}) *ReportEntryRepository_Create_Call {
	return &ReportEntryRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *ReportEntryRepository_Create_Call) Run(run func(ctx context.Context, entry *operations.ReportEntry)) *ReportEntryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.ReportEntry))
	})
	return _c
}

func (_c *ReportEntryRepository_Create_Call) Return(_a0 error) *ReportEntryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportEntryRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.ReportEntry) error) *ReportEntryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ReportEntryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportEntryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReportEntryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ReportEntryRepository_Expecter) Delete(ctx interface{}, id interface{}) *ReportEntryRepository_Delete_Call {
	return &ReportEntryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ReportEntryRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ReportEntryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportEntryRepository_Delete_Call) Return(_a0 error) *ReportEntryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportEntryRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ReportEntryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ReportEntryRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.ReportEntry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.ReportEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.ReportEntry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.ReportEntry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ReportEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportEntryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReportEntryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ReportEntryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ReportEntryRepository_GetByID_Call {
	return &ReportEntryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ReportEntryRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ReportEntryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportEntryRepository_GetByID_Call) Return(_a0 *operations.ReportEntry, _a1 error) *ReportEntryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportEntryRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.ReportEntry, error)) *ReportEntryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByReport provides a mock function with given fields: ctx, reportID
func (_m *ReportEntryRepository) ListByReport(ctx context.Context, reportID uuid.UUID) ([]operations.ReportEntry, error) {
	ret := _m.Called(ctx, reportID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReport")
	}

	var r0 []operations.ReportEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.ReportEntry, error)); ok {
		return rf(ctx, reportID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.ReportEntry); ok {
		r0 = rf(ctx, reportID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.ReportEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, reportID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportEntryRepository_ListByReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByReport'
type ReportEntryRepository_ListByReport_Call struct {
	*mock.Call
}

// ListByReport is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID uuid.UUID
func (_e *ReportEntryRepository_Expecter) ListByReport(ctx interface{}, reportID interface{}) *ReportEntryRepository_ListByReport_Call {
	return &ReportEntryRepository_ListByReport_Call{Call: _e.mock.On("ListByReport", ctx, reportID)}
}

func (_c *ReportEntryRepository_ListByReport_Call) Run(run func(ctx context.Context, reportID uuid.UUID)) *ReportEntryRepository_ListByReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportEntryRepository_ListByReport_Call) Return(_a0 []operations.ReportEntry, _a1 error) *ReportEntryRepository_ListByReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportEntryRepository_ListByReport_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.ReportEntry, error)) *ReportEntryRepository_ListByReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportEntryRepository creates a new instance of ReportEntryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportEntryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportEntryRepository {
	mock := &ReportEntryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeleteByReport provides a mock function with given fields: ctx, reportID
func (_m *ReportEntryRepository) DeleteByReport(ctx context.Context, reportID uuid.UUID) error {
	ret := _m.Called(ctx, reportID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, reportID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportEntryRepository_DeleteByReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByReport'
type ReportEntryRepository_DeleteByReport_Call struct {
	*mock.Call
}

// DeleteByReport is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID uuid.UUID
func (_e *ReportEntryRepository_Expecter) DeleteByReport(ctx interface{}, reportID interface{}) *ReportEntryRepository_DeleteByReport_Call {
	return &ReportEntryRepository_DeleteByReport_Call{Call: _e.mock.On("DeleteByReport", ctx, reportID)}
}

func (_c *ReportEntryRepository_DeleteByReport_Call) Run(run func(ctx context.Context, reportID uuid.UUID)) *ReportEntryRepository_DeleteByReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportEntryRepository_DeleteByReport_Call) Return(_a0 error) *ReportEntryRepository_DeleteByReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportEntryRepository_DeleteByReport_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ReportEntryRepository_DeleteByReport_Call {
	_c.Call.Return(run)
	return _c
}
