// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ReportImageRepository is an autogenerated mock type for the ReportImageRepository type
type ReportImageRepository struct {
	mock.Mock
}

type ReportImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportImageRepository) EXPECT() *ReportImageRepository_Expecter {
	return &ReportImageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, img
func (_m *ReportImageRepository) Create(ctx context.Context, img *operations.ReportImage) error {
	ret := _m.Called(ctx, img)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.ReportImage) error); ok {
		r0 = rf(ctx, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - img *operations.ReportImage
func (_e *ReportImageRepository_Expecter) Create(ctx interface{}, img interface{}) *ReportImageRepository_Create_Call {
	return &ReportImageRepository_Create_Call{Call: _e.mock.On("Create", ctx, img)}
}

func (_c *ReportImageRepository_Create_Call) Run(run func(ctx context.Context, img *operations.ReportImage)) *ReportImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.ReportImage))
	})
	return _c
}

func (_c *ReportImageRepository_Create_Call) Return(_a0 error) *ReportImageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportImageRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.ReportImage) error) *ReportImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ReportImageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReportImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ReportImageRepository_Expecter) Delete(ctx interface{}, id interface{}) *ReportImageRepository_Delete_Call {
	return &ReportImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ReportImageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ReportImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportImageRepository_Delete_Call) Return(_a0 error) *ReportImageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportImageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ReportImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ReportImageRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.ReportImage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.ReportImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.ReportImage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.ReportImage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ReportImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportImageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReportImageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ReportImageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ReportImageRepository_GetByID_Call {
	return &ReportImageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ReportImageRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ReportImageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportImageRepository_GetByID_Call) Return(_a0 *operations.ReportImage, _a1 error) *ReportImageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportImageRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.ReportImage, error)) *ReportImageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByReport provides a mock function with given fields: ctx, reportID
func (_m *ReportImageRepository) ListByReport(ctx context.Context, reportID uuid.UUID) ([]operations.ReportImage, error) {
	ret := _m.Called(ctx, reportID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReport")
	}

	var r0 []operations.ReportImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.ReportImage, error)); ok {
		return rf(ctx, reportID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.ReportImage); ok {
		r0 = rf(ctx, reportID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.ReportImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, reportID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportImageRepository_ListByReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByReport'
type ReportImageRepository_ListByReport_Call struct {
	*mock.Call
}

// ListByReport is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID uuid.UUID
func (_e *ReportImageRepository_Expecter) ListByReport(ctx interface{}, reportID interface{}) *ReportImageRepository_ListByReport_Call {
	return &ReportImageRepository_ListByReport_Call{Call: _e.mock.On("ListByReport", ctx, reportID)}
}

func (_c *ReportImageRepository_ListByReport_Call) Run(run func(ctx context.Context, reportID uuid.UUID)) *ReportImageRepository_ListByReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportImageRepository_ListByReport_Call) Return(_a0 []operations.ReportImage, _a1 error) *ReportImageRepository_ListByReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportImageRepository_ListByReport_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.ReportImage, error)) *ReportImageRepository_ListByReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportImageRepository creates a new instance of ReportImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportImageRepository {
	mock := &ReportImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
