// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	partners "localis-backend/internal/model/partners"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SLARepository is an autogenerated mock type for the SLARepository type
type SLARepository struct {
	mock.Mock
}

type SLARepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SLARepository) EXPECT() *SLARepository_Expecter {
	return &SLARepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sla
func (_m *SLARepository) Create(ctx context.Context, sla *partners.SLA) error {
	ret := _m.Called(ctx, sla)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *partners.SLA) error); ok {
		r0 = rf(ctx, sla)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SLARepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SLARepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sla *partners.SLA
func (_e *SLARepository_Expecter) Create(ctx interface{}, sla interface{}) *SLARepository_Create_Call {
	return &SLARepository_Create_Call{Call: _e.mock.On("Create", ctx, sla)}
}

func (_c *SLARepository_Create_Call) Run(run func(ctx context.Context, sla *partners.SLA)) *SLARepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*partners.SLA))
	})
	return _c
}

func (_c *SLARepository_Create_Call) Return(_a0 error) *SLARepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SLARepository_Create_Call) RunAndReturn(run func(context.Context, *partners.SLA) error) *SLARepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SLARepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SLARepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SLARepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *SLARepository_Expecter) Delete(ctx interface{}, id interface{}) *SLARepository_Delete_Call {
	return &SLARepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SLARepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *SLARepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SLARepository_Delete_Call) Return(_a0 error) *SLARepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SLARepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *SLARepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *SLARepository) GetByID(ctx context.Context, id uuid.UUID) (*partners.SLA, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *partners.SLA
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*partners.SLA, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *partners.SLA); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*partners.SLA)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SLARepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SLARepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *SLARepository_Expecter) GetByID(ctx interface{}, id interface{}) *SLARepository_GetByID_Call {
	return &SLARepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *SLARepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *SLARepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SLARepository_GetByID_Call) Return(_a0 *partners.SLA, _a1 error) *SLARepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SLARepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*partners.SLA, error)) *SLARepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPartner provides a mock function with given fields: ctx, partnerID
func (_m *SLARepository) ListByPartner(ctx context.Context, partnerID uuid.UUID) ([]partners.SLA, error) {
	ret := _m.Called(ctx, partnerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByPartner")
	}

	var r0 []partners.SLA
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]partners.SLA, error)); ok {
		return rf(ctx, partnerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []partners.SLA); ok {
		r0 = rf(ctx, partnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]partners.SLA)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, partnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SLARepository_ListByPartner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPartner'
type SLARepository_ListByPartner_Call struct {
	*mock.Call
}

// ListByPartner is a helper method to define mock.On call
//   - ctx context.Context
//   - partnerID uuid.UUID
func (_e *SLARepository_Expecter) ListByPartner(ctx interface{}, partnerID interface{}) *SLARepository_ListByPartner_Call {
	return &SLARepository_ListByPartner_Call{Call: _e.mock.On("ListByPartner", ctx, partnerID)}
}

func (_c *SLARepository_ListByPartner_Call) Run(run func(ctx context.Context, partnerID uuid.UUID)) *SLARepository_ListByPartner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SLARepository_ListByPartner_Call) Return(_a0 []partners.SLA, _a1 error) *SLARepository_ListByPartner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SLARepository_ListByPartner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]partners.SLA, error)) *SLARepository_ListByPartner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, sla
func (_m *SLARepository) Update(ctx context.Context, id uuid.UUID, sla *partners.SLA) error {
	ret := _m.Called(ctx, id, sla)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *partners.SLA) error); ok {
		r0 = rf(ctx, id, sla)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SLARepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SLARepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - sla *partners.SLA
func (_e *SLARepository_Expecter) Update(ctx interface{}, id interface{}, sla interface{}) *SLARepository_Update_Call {
	return &SLARepository_Update_Call{Call: _e.mock.On("Update", ctx, id, sla)}
}

func (_c *SLARepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, sla *partners.SLA)) *SLARepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*partners.SLA))
	})
	return _c
}

func (_c *SLARepository_Update_Call) Return(_a0 error) *SLARepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SLARepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *partners.SLA) error) *SLARepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSLARepository creates a new instance of SLARepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLARepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLARepository {
	mock := &SLARepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
