// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	customers "localis-backend/internal/model/customers"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TechCertificationRepository is an autogenerated mock type for the TechCertificationRepository type
type TechCertificationRepository struct {
	mock.Mock
}

type TechCertificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TechCertificationRepository) EXPECT() *TechCertificationRepository_Expecter {
	return &TechCertificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cert
func (_m *TechCertificationRepository) Create(ctx context.Context, cert *customers.TechCertification) error {
	ret := _m.Called(ctx, cert)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customers.TechCertification) error); ok {
		r0 = rf(ctx, cert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TechCertificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TechCertificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cert *customers.TechCertification
func (_e *TechCertificationRepository_Expecter) Create(ctx interface{}, cert interface{}) *TechCertificationRepository_Create_Call {
	return &TechCertificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, cert)}
}

func (_c *TechCertificationRepository_Create_Call) Run(run func(ctx context.Context, cert *customers.TechCertification)) *TechCertificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customers.TechCertification))
	})
	return _c
}

func (_c *TechCertificationRepository_Create_Call) Return(_a0 error) *TechCertificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TechCertificationRepository_Create_Call) RunAndReturn(run func(context.Context, *customers.TechCertification) error) *TechCertificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TechCertificationRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TechCertificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TechCertificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TechCertificationRepository_Expecter) Delete(ctx interface{}, id interface{}) *TechCertificationRepository_Delete_Call {
	return &TechCertificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TechCertificationRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TechCertificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TechCertificationRepository_Delete_Call) Return(_a0 error) *TechCertificationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TechCertificationRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TechCertificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TechCertificationRepository) GetByID(ctx context.Context, id uuid.UUID) (*customers.TechCertification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *customers.TechCertification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customers.TechCertification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customers.TechCertification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.TechCertification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TechCertificationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TechCertificationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TechCertificationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TechCertificationRepository_GetByID_Call {
	return &TechCertificationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TechCertificationRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TechCertificationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TechCertificationRepository_GetByID_Call) Return(_a0 *customers.TechCertification, _a1 error) *TechCertificationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TechCertificationRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*customers.TechCertification, error)) *TechCertificationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTech provides a mock function with given fields: ctx, techID
func (_m *TechCertificationRepository) ListByTech(ctx context.Context, techID uuid.UUID) ([]customers.TechCertification, error) {
	ret := _m.Called(ctx, techID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTech")
	}

	var r0 []customers.TechCertification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]customers.TechCertification, error)); ok {
		return rf(ctx, techID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []customers.TechCertification); ok {
		r0 = rf(ctx, techID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customers.TechCertification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, techID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TechCertificationRepository_ListByTech_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTech'
type TechCertificationRepository_ListByTech_Call struct {
	*mock.Call
}

// ListByTech is a helper method to define mock.On call
//   - ctx context.Context
//   - techID uuid.UUID
func (_e *TechCertificationRepository_Expecter) ListByTech(ctx interface{}, techID interface{}) *TechCertificationRepository_ListByTech_Call {
	return &TechCertificationRepository_ListByTech_Call{Call: _e.mock.On("ListByTech", ctx, techID)}
}

func (_c *TechCertificationRepository_ListByTech_Call) Run(run func(ctx context.Context, techID uuid.UUID)) *TechCertificationRepository_ListByTech_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TechCertificationRepository_ListByTech_Call) Return(_a0 []customers.TechCertification, _a1 error) *TechCertificationRepository_ListByTech_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TechCertificationRepository_ListByTech_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]customers.TechCertification, error)) *TechCertificationRepository_ListByTech_Call {
	_c.Call.Return(run)
	return _c
}

// NewTechCertificationRepository creates a new instance of TechCertificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTechCertificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TechCertificationRepository {
	mock := &TechCertificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
