// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	customers "localis-backend/internal/model/customers"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// TechnicianRepository is an autogenerated mock type for the TechnicianRepository type
type TechnicianRepository struct {
	mock.Mock
}

type TechnicianRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TechnicianRepository) EXPECT() *TechnicianRepository_Expecter {
	return &TechnicianRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tech
func (_m *TechnicianRepository) Create(ctx context.Context, tech *customers.Technician) error {
	ret := _m.Called(ctx, tech)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customers.Technician) error); ok {
		r0 = rf(ctx, tech)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TechnicianRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TechnicianRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tech *customers.Technician
func (_e *TechnicianRepository_Expecter) Create(ctx interface{}, tech interface{}) *TechnicianRepository_Create_Call {
	return &TechnicianRepository_Create_Call{Call: _e.mock.On("Create", ctx, tech)}
}

func (_c *TechnicianRepository_Create_Call) Run(run func(ctx context.Context, tech *customers.Technician)) *TechnicianRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customers.Technician))
	})
	return _c
}

func (_c *TechnicianRepository_Create_Call) Return(_a0 error) *TechnicianRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TechnicianRepository_Create_Call) RunAndReturn(run func(context.Context, *customers.Technician) error) *TechnicianRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TechnicianRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TechnicianRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TechnicianRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TechnicianRepository_Expecter) Delete(ctx interface{}, id interface{}) *TechnicianRepository_Delete_Call {
	return &TechnicianRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TechnicianRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TechnicianRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TechnicianRepository_Delete_Call) Return(_a0 error) *TechnicianRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TechnicianRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TechnicianRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TechnicianRepository) GetByID(ctx context.Context, id uuid.UUID) (*customers.Technician, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *customers.Technician
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customers.Technician, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customers.Technician); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.Technician)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TechnicianRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TechnicianRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TechnicianRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TechnicianRepository_GetByID_Call {
	return &TechnicianRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TechnicianRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TechnicianRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TechnicianRepository_GetByID_Call) Return(_a0 *customers.Technician, _a1 error) *TechnicianRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TechnicianRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*customers.Technician, error)) *TechnicianRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *TechnicianRepository) GetByUserID(ctx context.Context, userID string) (*customers.Technician, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *customers.Technician
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*customers.Technician, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *customers.Technician); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customers.Technician)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TechnicianRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type TechnicianRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TechnicianRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *TechnicianRepository_GetByUserID_Call {
	return &TechnicianRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *TechnicianRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *TechnicianRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TechnicianRepository_GetByUserID_Call) Return(_a0 *customers.Technician, _a1 error) *TechnicianRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TechnicianRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) (*customers.Technician, error)) *TechnicianRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *TechnicianRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[customers.Technician], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[customers.Technician]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[customers.Technician], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[customers.Technician]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[customers.Technician])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TechnicianRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TechnicianRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *TechnicianRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *TechnicianRepository_List_Call {
	return &TechnicianRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *TechnicianRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *TechnicianRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *TechnicianRepository_List_Call) Return(_a0 *repository.ListResult[customers.Technician], _a1 error) *TechnicianRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TechnicianRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[customers.Technician], error)) *TechnicianRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, tech
func (_m *TechnicianRepository) Update(ctx context.Context, id uuid.UUID, tech *customers.Technician) error {
	ret := _m.Called(ctx, id, tech)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *customers.Technician) error); ok {
		r0 = rf(ctx, id, tech)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TechnicianRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TechnicianRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tech *customers.Technician
func (_e *TechnicianRepository_Expecter) Update(ctx interface{}, id interface{}, tech interface{}) *TechnicianRepository_Update_Call {
	return &TechnicianRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, tech)}
}

func (_c *TechnicianRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, tech *customers.Technician)) *TechnicianRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*customers.Technician))
	})
	return _c
}

func (_c *TechnicianRepository_Update_Call) Return(_a0 error) *TechnicianRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TechnicianRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *customers.Technician) error) *TechnicianRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTechnicianRepository creates a new instance of TechnicianRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTechnicianRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TechnicianRepository {
	mock := &TechnicianRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
