// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// VehicleAssignmentRepository is an autogenerated mock type for the VehicleAssignmentRepository type
type VehicleAssignmentRepository struct {
	mock.Mock
}

type VehicleAssignmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VehicleAssignmentRepository) EXPECT() *VehicleAssignmentRepository_Expecter {
	return &VehicleAssignmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, va
func (_m *VehicleAssignmentRepository) Create(ctx context.Context, va *operations.VehicleAssignment) error {
	ret := _m.Called(ctx, va)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VehicleAssignment) error); ok {
		r0 = rf(ctx, va)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleAssignmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VehicleAssignmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - va *operations.VehicleAssignment
func (_e *VehicleAssignmentRepository_Expecter) Create(ctx interface{}, va interface{}) *VehicleAssignmentRepository_Create_Call {
	return &VehicleAssignmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, va)}
}

func (_c *VehicleAssignmentRepository_Create_Call) Run(run func(ctx context.Context, va *operations.VehicleAssignment)) *VehicleAssignmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VehicleAssignment))
	})
	return _c
}

func (_c *VehicleAssignmentRepository_Create_Call) Return(_a0 error) *VehicleAssignmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleAssignmentRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VehicleAssignment) error) *VehicleAssignmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VehicleAssignmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleAssignmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VehicleAssignmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VehicleAssignmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *VehicleAssignmentRepository_Delete_Call {
	return &VehicleAssignmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VehicleAssignmentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VehicleAssignmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VehicleAssignmentRepository_Delete_Call) Return(_a0 error) *VehicleAssignmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleAssignmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VehicleAssignmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VehicleAssignmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VehicleAssignment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VehicleAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VehicleAssignment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VehicleAssignment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VehicleAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VehicleAssignmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VehicleAssignmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VehicleAssignmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VehicleAssignmentRepository_GetByID_Call {
	return &VehicleAssignmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VehicleAssignmentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VehicleAssignmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VehicleAssignmentRepository_GetByID_Call) Return(_a0 *operations.VehicleAssignment, _a1 error) *VehicleAssignmentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VehicleAssignmentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VehicleAssignment, error)) *VehicleAssignmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *VehicleAssignmentRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[operations.VehicleAssignment], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[operations.VehicleAssignment]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[operations.VehicleAssignment], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[operations.VehicleAssignment]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[operations.VehicleAssignment])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VehicleAssignmentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VehicleAssignmentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *VehicleAssignmentRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *VehicleAssignmentRepository_List_Call {
	return &VehicleAssignmentRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *VehicleAssignmentRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *VehicleAssignmentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *VehicleAssignmentRepository_List_Call) Return(_a0 *repository.ListResult[operations.VehicleAssignment], _a1 error) *VehicleAssignmentRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VehicleAssignmentRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[operations.VehicleAssignment], error)) *VehicleAssignmentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, va
func (_m *VehicleAssignmentRepository) Update(ctx context.Context, id uuid.UUID, va *operations.VehicleAssignment) error {
	ret := _m.Called(ctx, id, va)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VehicleAssignment) error); ok {
		r0 = rf(ctx, id, va)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleAssignmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VehicleAssignmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - va *operations.VehicleAssignment
func (_e *VehicleAssignmentRepository_Expecter) Update(ctx interface{}, id interface{}, va interface{}) *VehicleAssignmentRepository_Update_Call {
	return &VehicleAssignmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, va)}
}

func (_c *VehicleAssignmentRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, va *operations.VehicleAssignment)) *VehicleAssignmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VehicleAssignment))
	})
	return _c
}

func (_c *VehicleAssignmentRepository_Update_Call) Return(_a0 error) *VehicleAssignmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleAssignmentRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VehicleAssignment) error) *VehicleAssignmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewVehicleAssignmentRepository creates a new instance of VehicleAssignmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicleAssignmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehicleAssignmentRepository {
	mock := &VehicleAssignmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
