// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	inventory "localis-backend/internal/model/inventory"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// VehicleRepository is an autogenerated mock type for the VehicleRepository type
type VehicleRepository struct {
	mock.Mock
}

type VehicleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VehicleRepository) EXPECT() *VehicleRepository_Expecter {
	return &VehicleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, vehicle
func (_m *VehicleRepository) Create(ctx context.Context, vehicle *inventory.Vehicle) error {
	ret := _m.Called(ctx, vehicle)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory.Vehicle) error); ok {
		r0 = rf(ctx, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VehicleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - vehicle *inventory.Vehicle
func (_e *VehicleRepository_Expecter) Create(ctx interface{}, vehicle interface{}) *VehicleRepository_Create_Call {
	return &VehicleRepository_Create_Call{Call: _e.mock.On("Create", ctx, vehicle)}
}

func (_c *VehicleRepository_Create_Call) Run(run func(ctx context.Context, vehicle *inventory.Vehicle)) *VehicleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*inventory.Vehicle))
	})
	return _c
}

func (_c *VehicleRepository_Create_Call) Return(_a0 error) *VehicleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleRepository_Create_Call) RunAndReturn(run func(context.Context, *inventory.Vehicle) error) *VehicleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VehicleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VehicleRepository_Expecter) Delete(ctx interface{}, id interface{}) *VehicleRepository_Delete_Call {
	return &VehicleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VehicleRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VehicleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VehicleRepository_Delete_Call) Return(_a0 error) *VehicleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VehicleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) GetByID(ctx context.Context, id uuid.UUID) (*inventory.Vehicle, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inventory.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*inventory.Vehicle, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *inventory.Vehicle); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VehicleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VehicleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VehicleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VehicleRepository_GetByID_Call {
	return &VehicleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VehicleRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VehicleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VehicleRepository_GetByID_Call) Return(_a0 *inventory.Vehicle, _a1 error) *VehicleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VehicleRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*inventory.Vehicle, error)) *VehicleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *VehicleRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[inventory.Vehicle], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[inventory.Vehicle]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[inventory.Vehicle], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[inventory.Vehicle]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[inventory.Vehicle])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VehicleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VehicleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *VehicleRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *VehicleRepository_List_Call {
	return &VehicleRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *VehicleRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *VehicleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *VehicleRepository_List_Call) Return(_a0 *repository.ListResult[inventory.Vehicle], _a1 error) *VehicleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VehicleRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[inventory.Vehicle], error)) *VehicleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, vehicle
func (_m *VehicleRepository) Update(ctx context.Context, id uuid.UUID, vehicle *inventory.Vehicle) error {
	ret := _m.Called(ctx, id, vehicle)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *inventory.Vehicle) error); ok {
		r0 = rf(ctx, id, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VehicleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - vehicle *inventory.Vehicle
func (_e *VehicleRepository_Expecter) Update(ctx interface{}, id interface{}, vehicle interface{}) *VehicleRepository_Update_Call {
	return &VehicleRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, vehicle)}
}

func (_c *VehicleRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, vehicle *inventory.Vehicle)) *VehicleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*inventory.Vehicle))
	})
	return _c
}

func (_c *VehicleRepository_Update_Call) Return(_a0 error) *VehicleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *inventory.Vehicle) error) *VehicleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInTx provides a mock function with given fields: ctx, tx, id, vehicle
func (_m *VehicleRepository) UpdateInTx(ctx context.Context, tx pgx.Tx, id uuid.UUID, vehicle *inventory.Vehicle) error {
	ret := _m.Called(ctx, tx, id, vehicle)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, *inventory.Vehicle) error); ok {
		r0 = rf(ctx, tx, id, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VehicleRepository_UpdateInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInTx'
type VehicleRepository_UpdateInTx_Call struct {
	*mock.Call
}

// UpdateInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
//   - vehicle *inventory.Vehicle
func (_e *VehicleRepository_Expecter) UpdateInTx(ctx interface{}, tx interface{}, id interface{}, vehicle interface{}) *VehicleRepository_UpdateInTx_Call {
	return &VehicleRepository_UpdateInTx_Call{Call: _e.mock.On("UpdateInTx", ctx, tx, id, vehicle)}
}

func (_c *VehicleRepository_UpdateInTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID, vehicle *inventory.Vehicle)) *VehicleRepository_UpdateInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID), args[3].(*inventory.Vehicle))
	})
	return _c
}

func (_c *VehicleRepository_UpdateInTx_Call) Return(_a0 error) *VehicleRepository_UpdateInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VehicleRepository_UpdateInTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID, *inventory.Vehicle) error) *VehicleRepository_UpdateInTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewVehicleRepository creates a new instance of VehicleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehicleRepository {
	mock := &VehicleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
