// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitPhotoRepository is an autogenerated mock type for the VisitPhotoRepository type
type VisitPhotoRepository struct {
	mock.Mock
}

type VisitPhotoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitPhotoRepository) EXPECT() *VisitPhotoRepository_Expecter {
	return &VisitPhotoRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, photo
func (_m *VisitPhotoRepository) Create(ctx context.Context, photo *operations.VisitPhoto) error {
	ret := _m.Called(ctx, photo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitPhoto) error); ok {
		r0 = rf(ctx, photo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitPhotoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitPhotoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - photo *operations.VisitPhoto
func (_e *VisitPhotoRepository_Expecter) Create(ctx interface{}, photo interface{}) *VisitPhotoRepository_Create_Call {
	return &VisitPhotoRepository_Create_Call{Call: _e.mock.On("Create", ctx, photo)}
}

func (_c *VisitPhotoRepository_Create_Call) Run(run func(ctx context.Context, photo *operations.VisitPhoto)) *VisitPhotoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitPhoto))
	})
	return _c
}

func (_c *VisitPhotoRepository_Create_Call) Return(_a0 error) *VisitPhotoRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitPhotoRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitPhoto) error) *VisitPhotoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitPhotoRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitPhotoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitPhotoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitPhotoRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitPhotoRepository_Delete_Call {
	return &VisitPhotoRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitPhotoRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitPhotoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitPhotoRepository_Delete_Call) Return(_a0 error) *VisitPhotoRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitPhotoRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitPhotoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitPhotoRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitPhoto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitPhoto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitPhoto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitPhoto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitPhoto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitPhotoRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitPhotoRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitPhotoRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitPhotoRepository_GetByID_Call {
	return &VisitPhotoRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitPhotoRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitPhotoRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitPhotoRepository_GetByID_Call) Return(_a0 *operations.VisitPhoto, _a1 error) *VisitPhotoRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitPhotoRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitPhoto, error)) *VisitPhotoRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitPhotoRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitPhoto, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitPhoto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitPhoto, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitPhoto); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitPhoto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitPhotoRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitPhotoRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitPhotoRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitPhotoRepository_ListByVisit_Call {
	return &VisitPhotoRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitPhotoRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitPhotoRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitPhotoRepository_ListByVisit_Call) Return(_a0 []operations.VisitPhoto, _a1 error) *VisitPhotoRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitPhotoRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitPhoto, error)) *VisitPhotoRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitPhotoRepository creates a new instance of VisitPhotoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitPhotoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitPhotoRepository {
	mock := &VisitPhotoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
