// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitMeasurementRepository is an autogenerated mock type for the VisitMeasurementRepository type
type VisitMeasurementRepository struct {
	mock.Mock
}

type VisitMeasurementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitMeasurementRepository) EXPECT() *VisitMeasurementRepository_Expecter {
	return &VisitMeasurementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *VisitMeasurementRepository) Create(ctx context.Context, m *operations.VisitMeasurement) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitMeasurement) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitMeasurementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitMeasurementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *operations.VisitMeasurement
func (_e *VisitMeasurementRepository_Expecter) Create(ctx interface{}, m interface{}) *VisitMeasurementRepository_Create_Call {
	return &VisitMeasurementRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *VisitMeasurementRepository_Create_Call) Run(run func(ctx context.Context, m *operations.VisitMeasurement)) *VisitMeasurementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitMeasurement))
	})
	return _c
}

func (_c *VisitMeasurementRepository_Create_Call) Return(_a0 error) *VisitMeasurementRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitMeasurementRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitMeasurement) error) *VisitMeasurementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitMeasurementRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitMeasurementRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitMeasurementRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitMeasurementRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitMeasurementRepository_Delete_Call {
	return &VisitMeasurementRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitMeasurementRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitMeasurementRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMeasurementRepository_Delete_Call) Return(_a0 error) *VisitMeasurementRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitMeasurementRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitMeasurementRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitMeasurementRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitMeasurement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitMeasurement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitMeasurement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitMeasurement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitMeasurement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitMeasurementRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitMeasurementRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitMeasurementRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitMeasurementRepository_GetByID_Call {
	return &VisitMeasurementRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitMeasurementRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitMeasurementRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMeasurementRepository_GetByID_Call) Return(_a0 *operations.VisitMeasurement, _a1 error) *VisitMeasurementRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitMeasurementRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitMeasurement, error)) *VisitMeasurementRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitMeasurementRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitMeasurement, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitMeasurement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitMeasurement, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitMeasurement); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitMeasurement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitMeasurementRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitMeasurementRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitMeasurementRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitMeasurementRepository_ListByVisit_Call {
	return &VisitMeasurementRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitMeasurementRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitMeasurementRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMeasurementRepository_ListByVisit_Call) Return(_a0 []operations.VisitMeasurement, _a1 error) *VisitMeasurementRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitMeasurementRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitMeasurement, error)) *VisitMeasurementRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *VisitMeasurementRepository) Update(ctx context.Context, id uuid.UUID, m *operations.VisitMeasurement) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VisitMeasurement) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitMeasurementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VisitMeasurementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - m *operations.VisitMeasurement
func (_e *VisitMeasurementRepository_Expecter) Update(ctx interface{}, id interface{}, m interface{}) *VisitMeasurementRepository_Update_Call {
	return &VisitMeasurementRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, m)}
}

func (_c *VisitMeasurementRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, m *operations.VisitMeasurement)) *VisitMeasurementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VisitMeasurement))
	})
	return _c
}

func (_c *VisitMeasurementRepository_Update_Call) Return(_a0 error) *VisitMeasurementRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitMeasurementRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VisitMeasurement) error) *VisitMeasurementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitMeasurementRepository creates a new instance of VisitMeasurementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitMeasurementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitMeasurementRepository {
	mock := &VisitMeasurementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
