// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// VisitReportRepository is an autogenerated mock type for the VisitReportRepository type
type VisitReportRepository struct {
	mock.Mock
}

type VisitReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitReportRepository) EXPECT() *VisitReportRepository_Expecter {
	return &VisitReportRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, report
func (_m *VisitReportRepository) Create(ctx context.Context, report *operations.VisitReport) error {
	ret := _m.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitReport) error); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitReportRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitReportRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - report *operations.VisitReport
func (_e *VisitReportRepository_Expecter) Create(ctx interface{}, report interface{}) *VisitReportRepository_Create_Call {
	return &VisitReportRepository_Create_Call{Call: _e.mock.On("Create", ctx, report)}
}

func (_c *VisitReportRepository_Create_Call) Run(run func(ctx context.Context, report *operations.VisitReport)) *VisitReportRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitReport))
	})
	return _c
}

func (_c *VisitReportRepository_Create_Call) Return(_a0 error) *VisitReportRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitReportRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitReport) error) *VisitReportRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitReportRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitReportRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitReportRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitReportRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitReportRepository_Delete_Call {
	return &VisitReportRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitReportRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitReportRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitReportRepository_Delete_Call) Return(_a0 error) *VisitReportRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitReportRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitReportRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitReportRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitReport, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitReport, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitReport); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitReportRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitReportRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitReportRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitReportRepository_GetByID_Call {
	return &VisitReportRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitReportRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitReportRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitReportRepository_GetByID_Call) Return(_a0 *operations.VisitReport, _a1 error) *VisitReportRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitReportRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitReport, error)) *VisitReportRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *VisitReportRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[operations.VisitReport], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[operations.VisitReport]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[operations.VisitReport], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[operations.VisitReport]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[operations.VisitReport])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitReportRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VisitReportRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *VisitReportRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *VisitReportRepository_List_Call {
	return &VisitReportRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *VisitReportRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *VisitReportRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *VisitReportRepository_List_Call) Return(_a0 *repository.ListResult[operations.VisitReport], _a1 error) *VisitReportRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitReportRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[operations.VisitReport], error)) *VisitReportRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitReportRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitReport, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitReport, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitReport); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitReportRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitReportRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitReportRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitReportRepository_ListByVisit_Call {
	return &VisitReportRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitReportRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitReportRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitReportRepository_ListByVisit_Call) Return(_a0 []operations.VisitReport, _a1 error) *VisitReportRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitReportRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitReport, error)) *VisitReportRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitReportRepository creates a new instance of VisitReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitReportRepository {
	mock := &VisitReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
