// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitChecklistMaterialRepository is an autogenerated mock type for the VisitChecklistMaterialRepository type
type VisitChecklistMaterialRepository struct {
	mock.Mock
}

type VisitChecklistMaterialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitChecklistMaterialRepository) EXPECT() *VisitChecklistMaterialRepository_Expecter {
	return &VisitChecklistMaterialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *VisitChecklistMaterialRepository) Create(ctx context.Context, item *operations.VisitChecklistMaterial) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitChecklistMaterial) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistMaterialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitChecklistMaterialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.VisitChecklistMaterial
func (_e *VisitChecklistMaterialRepository_Expecter) Create(ctx interface{}, item interface{}) *VisitChecklistMaterialRepository_Create_Call {
	return &VisitChecklistMaterialRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *VisitChecklistMaterialRepository_Create_Call) Run(run func(ctx context.Context, item *operations.VisitChecklistMaterial)) *VisitChecklistMaterialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitChecklistMaterial))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_Create_Call) Return(_a0 error) *VisitChecklistMaterialRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistMaterialRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitChecklistMaterial) error) *VisitChecklistMaterialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, items
func (_m *VisitChecklistMaterialRepository) CreateBatch(ctx context.Context, items []operations.VisitChecklistMaterial) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []operations.VisitChecklistMaterial) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistMaterialRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type VisitChecklistMaterialRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []operations.VisitChecklistMaterial
func (_e *VisitChecklistMaterialRepository_Expecter) CreateBatch(ctx interface{}, items interface{}) *VisitChecklistMaterialRepository_CreateBatch_Call {
	return &VisitChecklistMaterialRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, items)}
}

func (_c *VisitChecklistMaterialRepository_CreateBatch_Call) Run(run func(ctx context.Context, items []operations.VisitChecklistMaterial)) *VisitChecklistMaterialRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]operations.VisitChecklistMaterial))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_CreateBatch_Call) Return(_a0 error) *VisitChecklistMaterialRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistMaterialRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []operations.VisitChecklistMaterial) error) *VisitChecklistMaterialRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitChecklistMaterialRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistMaterialRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitChecklistMaterialRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistMaterialRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitChecklistMaterialRepository_Delete_Call {
	return &VisitChecklistMaterialRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitChecklistMaterialRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistMaterialRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_Delete_Call) Return(_a0 error) *VisitChecklistMaterialRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistMaterialRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitChecklistMaterialRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitChecklistMaterialRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitChecklistMaterial, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitChecklistMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitChecklistMaterial, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitChecklistMaterial); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitChecklistMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistMaterialRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitChecklistMaterialRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistMaterialRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitChecklistMaterialRepository_GetByID_Call {
	return &VisitChecklistMaterialRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitChecklistMaterialRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistMaterialRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_GetByID_Call) Return(_a0 *operations.VisitChecklistMaterial, _a1 error) *VisitChecklistMaterialRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistMaterialRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitChecklistMaterial, error)) *VisitChecklistMaterialRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitChecklistMaterialRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitChecklistMaterial, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitChecklistMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitChecklistMaterial, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitChecklistMaterial); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitChecklistMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistMaterialRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitChecklistMaterialRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitChecklistMaterialRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitChecklistMaterialRepository_ListByVisit_Call {
	return &VisitChecklistMaterialRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitChecklistMaterialRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitChecklistMaterialRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_ListByVisit_Call) Return(_a0 []operations.VisitChecklistMaterial, _a1 error) *VisitChecklistMaterialRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistMaterialRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitChecklistMaterial, error)) *VisitChecklistMaterialRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *VisitChecklistMaterialRepository) Update(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistMaterial) error {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VisitChecklistMaterial) error); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistMaterialRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VisitChecklistMaterialRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - item *operations.VisitChecklistMaterial
func (_e *VisitChecklistMaterialRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *VisitChecklistMaterialRepository_Update_Call {
	return &VisitChecklistMaterialRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *VisitChecklistMaterialRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistMaterial)) *VisitChecklistMaterialRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VisitChecklistMaterial))
	})
	return _c
}

func (_c *VisitChecklistMaterialRepository_Update_Call) Return(_a0 error) *VisitChecklistMaterialRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistMaterialRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VisitChecklistMaterial) error) *VisitChecklistMaterialRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitChecklistMaterialRepository creates a new instance of VisitChecklistMaterialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitChecklistMaterialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitChecklistMaterialRepository {
	mock := &VisitChecklistMaterialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
