// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitEPPUsageRepository is an autogenerated mock type for the VisitEPPUsageRepository type
type VisitEPPUsageRepository struct {
	mock.Mock
}

type VisitEPPUsageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitEPPUsageRepository) EXPECT() *VisitEPPUsageRepository_Expecter {
	return &VisitEPPUsageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, usage
func (_m *VisitEPPUsageRepository) Create(ctx context.Context, usage *operations.VisitEPPUsage) error {
	ret := _m.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitEPPUsage) error); ok {
		r0 = rf(ctx, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitEPPUsageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitEPPUsageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - usage *operations.VisitEPPUsage
func (_e *VisitEPPUsageRepository_Expecter) Create(ctx interface{}, usage interface{}) *VisitEPPUsageRepository_Create_Call {
	return &VisitEPPUsageRepository_Create_Call{Call: _e.mock.On("Create", ctx, usage)}
}

func (_c *VisitEPPUsageRepository_Create_Call) Run(run func(ctx context.Context, usage *operations.VisitEPPUsage)) *VisitEPPUsageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitEPPUsage))
	})
	return _c
}

func (_c *VisitEPPUsageRepository_Create_Call) Return(_a0 error) *VisitEPPUsageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitEPPUsageRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitEPPUsage) error) *VisitEPPUsageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitEPPUsageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitEPPUsageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitEPPUsageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitEPPUsageRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitEPPUsageRepository_Delete_Call {
	return &VisitEPPUsageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitEPPUsageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitEPPUsageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitEPPUsageRepository_Delete_Call) Return(_a0 error) *VisitEPPUsageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitEPPUsageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitEPPUsageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitEPPUsageRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitEPPUsage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitEPPUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitEPPUsage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitEPPUsage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitEPPUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitEPPUsageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitEPPUsageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitEPPUsageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitEPPUsageRepository_GetByID_Call {
	return &VisitEPPUsageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitEPPUsageRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitEPPUsageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitEPPUsageRepository_GetByID_Call) Return(_a0 *operations.VisitEPPUsage, _a1 error) *VisitEPPUsageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitEPPUsageRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitEPPUsage, error)) *VisitEPPUsageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitEPPUsageRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitEPPUsage, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitEPPUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitEPPUsage, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitEPPUsage); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitEPPUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitEPPUsageRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitEPPUsageRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitEPPUsageRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitEPPUsageRepository_ListByVisit_Call {
	return &VisitEPPUsageRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitEPPUsageRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitEPPUsageRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitEPPUsageRepository_ListByVisit_Call) Return(_a0 []operations.VisitEPPUsage, _a1 error) *VisitEPPUsageRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitEPPUsageRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitEPPUsage, error)) *VisitEPPUsageRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitEPPUsageRepository creates a new instance of VisitEPPUsageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitEPPUsageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitEPPUsageRepository {
	mock := &VisitEPPUsageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
