// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	repository "localis-backend/internal/repository"

	uuid "github.com/google/uuid"
)

// VisitRepository is an autogenerated mock type for the VisitRepository type
type VisitRepository struct {
	mock.Mock
}

type VisitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitRepository) EXPECT() *VisitRepository_Expecter {
	return &VisitRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, visit
func (_m *VisitRepository) Create(ctx context.Context, visit *operations.Visit) error {
	ret := _m.Called(ctx, visit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.Visit) error); ok {
		r0 = rf(ctx, visit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - visit *operations.Visit
func (_e *VisitRepository_Expecter) Create(ctx interface{}, visit interface{}) *VisitRepository_Create_Call {
	return &VisitRepository_Create_Call{Call: _e.mock.On("Create", ctx, visit)}
}

func (_c *VisitRepository_Create_Call) Run(run func(ctx context.Context, visit *operations.Visit)) *VisitRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.Visit))
	})
	return _c
}

func (_c *VisitRepository_Create_Call) Return(_a0 error) *VisitRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.Visit) error) *VisitRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitRepository_Delete_Call {
	return &VisitRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitRepository_Delete_Call) Return(_a0 error) *VisitRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.Visit, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.Visit, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.Visit); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitRepository_GetByID_Call {
	return &VisitRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitRepository_GetByID_Call) Return(_a0 *operations.Visit, _a1 error) *VisitRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.Visit, error)) *VisitRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *VisitRepository) List(ctx context.Context, limit int, offset int) (*repository.ListResult[operations.Visit], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListResult[operations.Visit]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListResult[operations.Visit], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListResult[operations.Visit]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListResult[operations.Visit])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VisitRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *VisitRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *VisitRepository_List_Call {
	return &VisitRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *VisitRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *VisitRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *VisitRepository_List_Call) Return(_a0 *repository.ListResult[operations.Visit], _a1 error) *VisitRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListResult[operations.Visit], error)) *VisitRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, visit
func (_m *VisitRepository) Update(ctx context.Context, id uuid.UUID, visit *operations.Visit) error {
	ret := _m.Called(ctx, id, visit)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.Visit) error); ok {
		r0 = rf(ctx, id, visit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VisitRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - visit *operations.Visit
func (_e *VisitRepository_Expecter) Update(ctx interface{}, id interface{}, visit interface{}) *VisitRepository_Update_Call {
	return &VisitRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, visit)}
}

func (_c *VisitRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, visit *operations.Visit)) *VisitRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.Visit))
	})
	return _c
}

func (_c *VisitRepository_Update_Call) Return(_a0 error) *VisitRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.Visit) error) *VisitRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInTx provides a mock function with given fields: ctx, tx, id, visit
func (_m *VisitRepository) UpdateInTx(ctx context.Context, tx pgx.Tx, id uuid.UUID, visit *operations.Visit) error {
	ret := _m.Called(ctx, tx, id, visit)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, *operations.Visit) error); ok {
		r0 = rf(ctx, tx, id, visit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_UpdateInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInTx'
type VisitRepository_UpdateInTx_Call struct {
	*mock.Call
}

// UpdateInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
//   - visit *operations.Visit
func (_e *VisitRepository_Expecter) UpdateInTx(ctx interface{}, tx interface{}, id interface{}, visit interface{}) *VisitRepository_UpdateInTx_Call {
	return &VisitRepository_UpdateInTx_Call{Call: _e.mock.On("UpdateInTx", ctx, tx, id, visit)}
}

func (_c *VisitRepository_UpdateInTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID, visit *operations.Visit)) *VisitRepository_UpdateInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID), args[3].(*operations.Visit))
	})
	return _c
}

func (_c *VisitRepository_UpdateInTx_Call) Return(_a0 error) *VisitRepository_UpdateInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_UpdateInTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID, *operations.Visit) error) *VisitRepository_UpdateInTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitRepository creates a new instance of VisitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitRepository {
	mock := &VisitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
