// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitChecklistEPPRepository is an autogenerated mock type for the VisitChecklistEPPRepository type
type VisitChecklistEPPRepository struct {
	mock.Mock
}

type VisitChecklistEPPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitChecklistEPPRepository) EXPECT() *VisitChecklistEPPRepository_Expecter {
	return &VisitChecklistEPPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *VisitChecklistEPPRepository) Create(ctx context.Context, item *operations.VisitChecklistEPP) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitChecklistEPP) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistEPPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitChecklistEPPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.VisitChecklistEPP
func (_e *VisitChecklistEPPRepository_Expecter) Create(ctx interface{}, item interface{}) *VisitChecklistEPPRepository_Create_Call {
	return &VisitChecklistEPPRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *VisitChecklistEPPRepository_Create_Call) Run(run func(ctx context.Context, item *operations.VisitChecklistEPP)) *VisitChecklistEPPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitChecklistEPP))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_Create_Call) Return(_a0 error) *VisitChecklistEPPRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistEPPRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitChecklistEPP) error) *VisitChecklistEPPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, items
func (_m *VisitChecklistEPPRepository) CreateBatch(ctx context.Context, items []operations.VisitChecklistEPP) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []operations.VisitChecklistEPP) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistEPPRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type VisitChecklistEPPRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []operations.VisitChecklistEPP
func (_e *VisitChecklistEPPRepository_Expecter) CreateBatch(ctx interface{}, items interface{}) *VisitChecklistEPPRepository_CreateBatch_Call {
	return &VisitChecklistEPPRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, items)}
}

func (_c *VisitChecklistEPPRepository_CreateBatch_Call) Run(run func(ctx context.Context, items []operations.VisitChecklistEPP)) *VisitChecklistEPPRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]operations.VisitChecklistEPP))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_CreateBatch_Call) Return(_a0 error) *VisitChecklistEPPRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistEPPRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []operations.VisitChecklistEPP) error) *VisitChecklistEPPRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitChecklistEPPRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistEPPRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitChecklistEPPRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistEPPRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitChecklistEPPRepository_Delete_Call {
	return &VisitChecklistEPPRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitChecklistEPPRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistEPPRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_Delete_Call) Return(_a0 error) *VisitChecklistEPPRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistEPPRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitChecklistEPPRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitChecklistEPPRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitChecklistEPP, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitChecklistEPP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitChecklistEPP, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitChecklistEPP); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitChecklistEPP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistEPPRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitChecklistEPPRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistEPPRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitChecklistEPPRepository_GetByID_Call {
	return &VisitChecklistEPPRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitChecklistEPPRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistEPPRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_GetByID_Call) Return(_a0 *operations.VisitChecklistEPP, _a1 error) *VisitChecklistEPPRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistEPPRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitChecklistEPP, error)) *VisitChecklistEPPRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitChecklistEPPRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitChecklistEPP, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitChecklistEPP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitChecklistEPP, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitChecklistEPP); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitChecklistEPP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistEPPRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitChecklistEPPRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitChecklistEPPRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitChecklistEPPRepository_ListByVisit_Call {
	return &VisitChecklistEPPRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitChecklistEPPRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitChecklistEPPRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_ListByVisit_Call) Return(_a0 []operations.VisitChecklistEPP, _a1 error) *VisitChecklistEPPRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistEPPRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitChecklistEPP, error)) *VisitChecklistEPPRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *VisitChecklistEPPRepository) Update(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistEPP) error {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VisitChecklistEPP) error); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistEPPRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VisitChecklistEPPRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - item *operations.VisitChecklistEPP
func (_e *VisitChecklistEPPRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *VisitChecklistEPPRepository_Update_Call {
	return &VisitChecklistEPPRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *VisitChecklistEPPRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistEPP)) *VisitChecklistEPPRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VisitChecklistEPP))
	})
	return _c
}

func (_c *VisitChecklistEPPRepository_Update_Call) Return(_a0 error) *VisitChecklistEPPRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistEPPRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VisitChecklistEPP) error) *VisitChecklistEPPRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitChecklistEPPRepository creates a new instance of VisitChecklistEPPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitChecklistEPPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitChecklistEPPRepository {
	mock := &VisitChecklistEPPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
