// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitRentalRepository is an autogenerated mock type for the VisitRentalRepository type
type VisitRentalRepository struct {
	mock.Mock
}

type VisitRentalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitRentalRepository) EXPECT() *VisitRentalRepository_Expecter {
	return &VisitRentalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, r
func (_m *VisitRentalRepository) Create(ctx context.Context, r *operations.VisitRental) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitRental) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRentalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitRentalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *operations.VisitRental
func (_e *VisitRentalRepository_Expecter) Create(ctx interface{}, r interface{}) *VisitRentalRepository_Create_Call {
	return &VisitRentalRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *VisitRentalRepository_Create_Call) Run(run func(ctx context.Context, r *operations.VisitRental)) *VisitRentalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitRental))
	})
	return _c
}

func (_c *VisitRentalRepository_Create_Call) Return(_a0 error) *VisitRentalRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRentalRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitRental) error) *VisitRentalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitRentalRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRentalRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitRentalRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitRentalRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitRentalRepository_Delete_Call {
	return &VisitRentalRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitRentalRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitRentalRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitRentalRepository_Delete_Call) Return(_a0 error) *VisitRentalRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRentalRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitRentalRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitRentalRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitRental, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitRental
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitRental, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitRental); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitRental)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRentalRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitRentalRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitRentalRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitRentalRepository_GetByID_Call {
	return &VisitRentalRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitRentalRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitRentalRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitRentalRepository_GetByID_Call) Return(_a0 *operations.VisitRental, _a1 error) *VisitRentalRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRentalRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitRental, error)) *VisitRentalRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitRentalRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitRental, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitRental
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitRental, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitRental); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitRental)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRentalRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitRentalRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitRentalRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitRentalRepository_ListByVisit_Call {
	return &VisitRentalRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitRentalRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitRentalRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitRentalRepository_ListByVisit_Call) Return(_a0 []operations.VisitRental, _a1 error) *VisitRentalRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRentalRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitRental, error)) *VisitRentalRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitRentalRepository creates a new instance of VisitRentalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitRentalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitRentalRepository {
	mock := &VisitRentalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
