// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitAssignmentRepository is an autogenerated mock type for the VisitAssignmentRepository type
type VisitAssignmentRepository struct {
	mock.Mock
}

type VisitAssignmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitAssignmentRepository) EXPECT() *VisitAssignmentRepository_Expecter {
	return &VisitAssignmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *VisitAssignmentRepository) Create(ctx context.Context, a *operations.VisitAssignment) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitAssignment) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitAssignmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitAssignmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *operations.VisitAssignment
func (_e *VisitAssignmentRepository_Expecter) Create(ctx interface{}, a interface{}) *VisitAssignmentRepository_Create_Call {
	return &VisitAssignmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *VisitAssignmentRepository_Create_Call) Run(run func(ctx context.Context, a *operations.VisitAssignment)) *VisitAssignmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitAssignment))
	})
	return _c
}

func (_c *VisitAssignmentRepository_Create_Call) Return(_a0 error) *VisitAssignmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitAssignmentRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitAssignment) error) *VisitAssignmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitAssignmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitAssignmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitAssignmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitAssignmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitAssignmentRepository_Delete_Call {
	return &VisitAssignmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitAssignmentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitAssignmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitAssignmentRepository_Delete_Call) Return(_a0 error) *VisitAssignmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitAssignmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitAssignmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitAssignmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitAssignment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitAssignment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitAssignment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitAssignmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitAssignmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitAssignmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitAssignmentRepository_GetByID_Call {
	return &VisitAssignmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitAssignmentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitAssignmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitAssignmentRepository_GetByID_Call) Return(_a0 *operations.VisitAssignment, _a1 error) *VisitAssignmentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitAssignmentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitAssignment, error)) *VisitAssignmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitAssignmentRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitAssignment, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitAssignment, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitAssignment); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitAssignmentRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitAssignmentRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitAssignmentRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitAssignmentRepository_ListByVisit_Call {
	return &VisitAssignmentRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitAssignmentRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitAssignmentRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitAssignmentRepository_ListByVisit_Call) Return(_a0 []operations.VisitAssignment, _a1 error) *VisitAssignmentRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitAssignmentRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitAssignment, error)) *VisitAssignmentRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitAssignmentRepository creates a new instance of VisitAssignmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitAssignmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitAssignmentRepository {
	mock := &VisitAssignmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
