// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitMaterialUsageRepository is an autogenerated mock type for the VisitMaterialUsageRepository type
type VisitMaterialUsageRepository struct {
	mock.Mock
}

type VisitMaterialUsageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitMaterialUsageRepository) EXPECT() *VisitMaterialUsageRepository_Expecter {
	return &VisitMaterialUsageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, usage
func (_m *VisitMaterialUsageRepository) Create(ctx context.Context, usage *operations.VisitMaterialUsage) error {
	ret := _m.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitMaterialUsage) error); ok {
		r0 = rf(ctx, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitMaterialUsageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitMaterialUsageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - usage *operations.VisitMaterialUsage
func (_e *VisitMaterialUsageRepository_Expecter) Create(ctx interface{}, usage interface{}) *VisitMaterialUsageRepository_Create_Call {
	return &VisitMaterialUsageRepository_Create_Call{Call: _e.mock.On("Create", ctx, usage)}
}

func (_c *VisitMaterialUsageRepository_Create_Call) Run(run func(ctx context.Context, usage *operations.VisitMaterialUsage)) *VisitMaterialUsageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitMaterialUsage))
	})
	return _c
}

func (_c *VisitMaterialUsageRepository_Create_Call) Return(_a0 error) *VisitMaterialUsageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitMaterialUsageRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitMaterialUsage) error) *VisitMaterialUsageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitMaterialUsageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitMaterialUsageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitMaterialUsageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitMaterialUsageRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitMaterialUsageRepository_Delete_Call {
	return &VisitMaterialUsageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitMaterialUsageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitMaterialUsageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMaterialUsageRepository_Delete_Call) Return(_a0 error) *VisitMaterialUsageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitMaterialUsageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitMaterialUsageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitMaterialUsageRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitMaterialUsage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitMaterialUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitMaterialUsage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitMaterialUsage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitMaterialUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitMaterialUsageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitMaterialUsageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitMaterialUsageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitMaterialUsageRepository_GetByID_Call {
	return &VisitMaterialUsageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitMaterialUsageRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitMaterialUsageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMaterialUsageRepository_GetByID_Call) Return(_a0 *operations.VisitMaterialUsage, _a1 error) *VisitMaterialUsageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitMaterialUsageRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitMaterialUsage, error)) *VisitMaterialUsageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitMaterialUsageRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitMaterialUsage, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitMaterialUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitMaterialUsage, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitMaterialUsage); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitMaterialUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitMaterialUsageRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitMaterialUsageRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitMaterialUsageRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitMaterialUsageRepository_ListByVisit_Call {
	return &VisitMaterialUsageRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitMaterialUsageRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitMaterialUsageRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitMaterialUsageRepository_ListByVisit_Call) Return(_a0 []operations.VisitMaterialUsage, _a1 error) *VisitMaterialUsageRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitMaterialUsageRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitMaterialUsage, error)) *VisitMaterialUsageRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitMaterialUsageRepository creates a new instance of VisitMaterialUsageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitMaterialUsageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitMaterialUsageRepository {
	mock := &VisitMaterialUsageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
