// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitToolUsageRepository is an autogenerated mock type for the VisitToolUsageRepository type
type VisitToolUsageRepository struct {
	mock.Mock
}

type VisitToolUsageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitToolUsageRepository) EXPECT() *VisitToolUsageRepository_Expecter {
	return &VisitToolUsageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, usage
func (_m *VisitToolUsageRepository) Create(ctx context.Context, usage *operations.VisitToolUsage) error {
	ret := _m.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitToolUsage) error); ok {
		r0 = rf(ctx, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitToolUsageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitToolUsageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - usage *operations.VisitToolUsage
func (_e *VisitToolUsageRepository_Expecter) Create(ctx interface{}, usage interface{}) *VisitToolUsageRepository_Create_Call {
	return &VisitToolUsageRepository_Create_Call{Call: _e.mock.On("Create", ctx, usage)}
}

func (_c *VisitToolUsageRepository_Create_Call) Run(run func(ctx context.Context, usage *operations.VisitToolUsage)) *VisitToolUsageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitToolUsage))
	})
	return _c
}

func (_c *VisitToolUsageRepository_Create_Call) Return(_a0 error) *VisitToolUsageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitToolUsageRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitToolUsage) error) *VisitToolUsageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitToolUsageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitToolUsageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitToolUsageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitToolUsageRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitToolUsageRepository_Delete_Call {
	return &VisitToolUsageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitToolUsageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitToolUsageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitToolUsageRepository_Delete_Call) Return(_a0 error) *VisitToolUsageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitToolUsageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitToolUsageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitToolUsageRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitToolUsage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitToolUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitToolUsage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitToolUsage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitToolUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitToolUsageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitToolUsageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitToolUsageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitToolUsageRepository_GetByID_Call {
	return &VisitToolUsageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitToolUsageRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitToolUsageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitToolUsageRepository_GetByID_Call) Return(_a0 *operations.VisitToolUsage, _a1 error) *VisitToolUsageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitToolUsageRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitToolUsage, error)) *VisitToolUsageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitToolUsageRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitToolUsage, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitToolUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitToolUsage, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitToolUsage); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitToolUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitToolUsageRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitToolUsageRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitToolUsageRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitToolUsageRepository_ListByVisit_Call {
	return &VisitToolUsageRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitToolUsageRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitToolUsageRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitToolUsageRepository_ListByVisit_Call) Return(_a0 []operations.VisitToolUsage, _a1 error) *VisitToolUsageRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitToolUsageRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitToolUsage, error)) *VisitToolUsageRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitToolUsageRepository creates a new instance of VisitToolUsageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitToolUsageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitToolUsageRepository {
	mock := &VisitToolUsageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
