// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VisitChecklistToolRepository is an autogenerated mock type for the VisitChecklistToolRepository type
type VisitChecklistToolRepository struct {
	mock.Mock
}

type VisitChecklistToolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitChecklistToolRepository) EXPECT() *VisitChecklistToolRepository_Expecter {
	return &VisitChecklistToolRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *VisitChecklistToolRepository) Create(ctx context.Context, item *operations.VisitChecklistTool) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitChecklistTool) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistToolRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitChecklistToolRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *operations.VisitChecklistTool
func (_e *VisitChecklistToolRepository_Expecter) Create(ctx interface{}, item interface{}) *VisitChecklistToolRepository_Create_Call {
	return &VisitChecklistToolRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *VisitChecklistToolRepository_Create_Call) Run(run func(ctx context.Context, item *operations.VisitChecklistTool)) *VisitChecklistToolRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitChecklistTool))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_Create_Call) Return(_a0 error) *VisitChecklistToolRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistToolRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitChecklistTool) error) *VisitChecklistToolRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, items
func (_m *VisitChecklistToolRepository) CreateBatch(ctx context.Context, items []operations.VisitChecklistTool) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []operations.VisitChecklistTool) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistToolRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type VisitChecklistToolRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []operations.VisitChecklistTool
func (_e *VisitChecklistToolRepository_Expecter) CreateBatch(ctx interface{}, items interface{}) *VisitChecklistToolRepository_CreateBatch_Call {
	return &VisitChecklistToolRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, items)}
}

func (_c *VisitChecklistToolRepository_CreateBatch_Call) Run(run func(ctx context.Context, items []operations.VisitChecklistTool)) *VisitChecklistToolRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]operations.VisitChecklistTool))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_CreateBatch_Call) Return(_a0 error) *VisitChecklistToolRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistToolRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []operations.VisitChecklistTool) error) *VisitChecklistToolRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitChecklistToolRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistToolRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitChecklistToolRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistToolRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitChecklistToolRepository_Delete_Call {
	return &VisitChecklistToolRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitChecklistToolRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistToolRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_Delete_Call) Return(_a0 error) *VisitChecklistToolRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistToolRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *VisitChecklistToolRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VisitChecklistToolRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitChecklistTool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitChecklistTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitChecklistTool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitChecklistTool); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitChecklistTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistToolRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type VisitChecklistToolRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *VisitChecklistToolRepository_Expecter) GetByID(ctx interface{}, id interface{}) *VisitChecklistToolRepository_GetByID_Call {
	return &VisitChecklistToolRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *VisitChecklistToolRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *VisitChecklistToolRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_GetByID_Call) Return(_a0 *operations.VisitChecklistTool, _a1 error) *VisitChecklistToolRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistToolRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitChecklistTool, error)) *VisitChecklistToolRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVisit provides a mock function with given fields: ctx, visitID
func (_m *VisitChecklistToolRepository) ListByVisit(ctx context.Context, visitID uuid.UUID) ([]operations.VisitChecklistTool, error) {
	ret := _m.Called(ctx, visitID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVisit")
	}

	var r0 []operations.VisitChecklistTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]operations.VisitChecklistTool, error)); ok {
		return rf(ctx, visitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []operations.VisitChecklistTool); ok {
		r0 = rf(ctx, visitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]operations.VisitChecklistTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, visitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitChecklistToolRepository_ListByVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVisit'
type VisitChecklistToolRepository_ListByVisit_Call struct {
	*mock.Call
}

// ListByVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - visitID uuid.UUID
func (_e *VisitChecklistToolRepository_Expecter) ListByVisit(ctx interface{}, visitID interface{}) *VisitChecklistToolRepository_ListByVisit_Call {
	return &VisitChecklistToolRepository_ListByVisit_Call{Call: _e.mock.On("ListByVisit", ctx, visitID)}
}

func (_c *VisitChecklistToolRepository_ListByVisit_Call) Run(run func(ctx context.Context, visitID uuid.UUID)) *VisitChecklistToolRepository_ListByVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_ListByVisit_Call) Return(_a0 []operations.VisitChecklistTool, _a1 error) *VisitChecklistToolRepository_ListByVisit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitChecklistToolRepository_ListByVisit_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]operations.VisitChecklistTool, error)) *VisitChecklistToolRepository_ListByVisit_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *VisitChecklistToolRepository) Update(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistTool) error {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VisitChecklistTool) error); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitChecklistToolRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VisitChecklistToolRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - item *operations.VisitChecklistTool
func (_e *VisitChecklistToolRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *VisitChecklistToolRepository_Update_Call {
	return &VisitChecklistToolRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *VisitChecklistToolRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, item *operations.VisitChecklistTool)) *VisitChecklistToolRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VisitChecklistTool))
	})
	return _c
}

func (_c *VisitChecklistToolRepository_Update_Call) Return(_a0 error) *VisitChecklistToolRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitChecklistToolRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VisitChecklistTool) error) *VisitChecklistToolRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitChecklistToolRepository creates a new instance of VisitChecklistToolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitChecklistToolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitChecklistToolRepository {
	mock := &VisitChecklistToolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
