// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	operations "localis-backend/internal/model/operations"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVisitTypeRepository is an autogenerated mock type for the VisitTypeRepository type
type MockVisitTypeRepository struct {
	mock.Mock
}

type MockVisitTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitTypeRepository) EXPECT() *MockVisitTypeRepository_Expecter {
	return &MockVisitTypeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, vt
func (_m *MockVisitTypeRepository) Create(ctx context.Context, vt *operations.VisitType) error {
	ret := _m.Called(ctx, vt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *operations.VisitType) error); ok {
		r0 = rf(ctx, vt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVisitTypeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVisitTypeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - vt *operations.VisitType
func (_e *MockVisitTypeRepository_Expecter) Create(ctx interface{}, vt interface{}) *MockVisitTypeRepository_Create_Call {
	return &MockVisitTypeRepository_Create_Call{Call: _e.mock.On("Create", ctx, vt)}
}

func (_c *MockVisitTypeRepository_Create_Call) Run(run func(ctx context.Context, vt *operations.VisitType)) *MockVisitTypeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*operations.VisitType))
	})
	return _c
}

func (_c *MockVisitTypeRepository_Create_Call) Return(_a0 error) *MockVisitTypeRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVisitTypeRepository_Create_Call) RunAndReturn(run func(context.Context, *operations.VisitType) error) *MockVisitTypeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockVisitTypeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVisitTypeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVisitTypeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVisitTypeRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockVisitTypeRepository_Delete_Call {
	return &MockVisitTypeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVisitTypeRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVisitTypeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVisitTypeRepository_Delete_Call) Return(_a0 error) *MockVisitTypeRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVisitTypeRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockVisitTypeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockVisitTypeRepository) GetByID(ctx context.Context, id uuid.UUID) (*operations.VisitType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *operations.VisitType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*operations.VisitType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *operations.VisitType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.VisitType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVisitTypeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVisitTypeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVisitTypeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockVisitTypeRepository_GetByID_Call {
	return &MockVisitTypeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVisitTypeRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVisitTypeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVisitTypeRepository_GetByID_Call) Return(_a0 *operations.VisitType, _a1 error) *MockVisitTypeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVisitTypeRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*operations.VisitType, error)) *MockVisitTypeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockVisitTypeRepository) List(ctx context.Context, limit int, offset int) (*ListResult[operations.VisitType], error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ListResult[operations.VisitType]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*ListResult[operations.VisitType], error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *ListResult[operations.VisitType]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListResult[operations.VisitType])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVisitTypeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVisitTypeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockVisitTypeRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockVisitTypeRepository_List_Call {
	return &MockVisitTypeRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockVisitTypeRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockVisitTypeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockVisitTypeRepository_List_Call) Return(_a0 *ListResult[operations.VisitType], _a1 error) *MockVisitTypeRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVisitTypeRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*ListResult[operations.VisitType], error)) *MockVisitTypeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, vt
func (_m *MockVisitTypeRepository) Update(ctx context.Context, id uuid.UUID, vt *operations.VisitType) error {
	ret := _m.Called(ctx, id, vt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *operations.VisitType) error); ok {
		r0 = rf(ctx, id, vt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVisitTypeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVisitTypeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - vt *operations.VisitType
func (_e *MockVisitTypeRepository_Expecter) Update(ctx interface{}, id interface{}, vt interface{}) *MockVisitTypeRepository_Update_Call {
	return &MockVisitTypeRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, vt)}
}

func (_c *MockVisitTypeRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, vt *operations.VisitType)) *MockVisitTypeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*operations.VisitType))
	})
	return _c
}

func (_c *MockVisitTypeRepository_Update_Call) Return(_a0 error) *MockVisitTypeRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVisitTypeRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *operations.VisitType) error) *MockVisitTypeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitTypeRepository creates a new instance of MockVisitTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitTypeRepository {
	mock := &MockVisitTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
